- src/world/Creature.h
- src/world/ObjectStorage.cpp
"Invalid format in creature_names (24/25), loading anyway because we have enough data."
> Core/Storage: Fix, the message warning.

- sql/world_updates/2015-03-24_01_player_xp_for_level.sql
- src/world/ObjectMgr.cpp
- src/world/ObjectMgr.h
- src/world/ObjectStorage.cpp
- src/world/Player.cpp
- src/world/Player.h
- src/world/Unit.cpp
- src/world/Unit.h
Please discuss this change. Is this the way AscEmu would handle information?
> CHANGED: Player xp goes to db.

- src/scripts/QuestScripts/Quest_DeathKnight.cpp
Merged gryphons gossip scripts into one
Implemented quest 12593 (in service of lich king) script
> merged easywow death knight quests scripts

- src/world/TransporterHandler.cpp
after few tests on 3 transporters serveral times i fixed creatures move
to wrong pos
@DankoDJ
> fixed creature problem

- src/world/DBC/DBCStores.cpp
- src/world/DBC/DBCStores.h
- src/world/DBC/DBCStructures.hpp
- src/world/LfgHandler.cpp
- src/world/LfgMgr.cpp
- src/world/Quest.cpp
- src/world/Quest.h
someone needs to look at linux error at dungeon reward?
> fixed looking for random dungeon added random dungeon reward showing

- sql/world_updates/2015-12-15_01_misc_update.sql
- src/world/Master.h
Thanks @Nupper
https://github.com/AscEmu/AscEmu/issues/197#issuecomment-164848290
Relocation NPC:
* Magister Surdiel <Wintergrasp Battle-Mage>
* High Arcanist Savor
* Horde Warbringer
> Fix - Missing structures. (Portal Isle of Conquest)

- .travis.yml
sorry about this misstake, i'm still new in YAML language and operators are hardly documented... found information about correct operators only in old pdf books
> travis correction

- src/scripts/QuestScripts/Quest_DeathKnight.cpp
"Preperation for battle" quest credit will given by spell effect instead of using server hooks
added simple comments for quest "In service of the Lich King"
> small cleanup in death knight starting zone

- src/world/GameEventMgr.cpp
- src/world/SpellManagement/SpellCustomizations.cpp
- src/world/SpellMgr.cpp
- src/world/TransporterHandler.cpp
* Fixed most cases where memory is leaked
* Fixed possible failures with STL functions misstatch (for example:
std::count, http://www.cplusplus.com/reference/algorithm/count/)
> Fixed some data loads

- sql/world_updates/2016-03-18_01_misc.sql
- src/shared/Storage.h
- src/world/Master.h
* Fix in the message of "Dual Specialization"
* Related to the incidence https://github.com/AscEmu/AscEmu/issues/225
> * Small correction path library MainServerDefines.h

- src/world/Units/Players/Player.cpp
- src/world/Units/Players/Player.h
- src/world/Units/Players/PlayerDefines.hpp
https://github.com/AscEmu/AscEmu/commit/86cc3dd69d22c8e4d383d8f967ffc178d155aa5a
> Replaced magic numbers with enum values MirrorTimerType

- sql/world_updates/2016-11-03_01_misc_spelltargetconstraints.sql
- src/scripts/QuestScripts/Quest_BoreanTundra.cpp
- src/world/Objects/ObjectMgr.cpp
- src/world/Server/Master.h
- src/world/Spell/Spell.cpp
- src/world/Spell/Spell.h
Added the Ability to Cast Spells near Creatures / Gos needed for certain
quests where you need to cast a spell near a certain place
> Spells on Invisible Creatures ( Mostly Scripted )

- sql/world_updates/2017-01-08_01_npc_script_text.sql
- src/scripts/InstanceScripts/Instance_TheStockade.cpp
- src/scripts/InstanceScripts/Instance_TheStockade.h
- src/world/Server/Master.h
The Stockades dungeon rewrite :
Boss :
Trash :
Note : I didin't add Trash flee script because we don't have a random flee function  and settings manually their path would look super weird when lots of them flee using the same path.
thanks to ChronoEmu for the enrage part
> Rewrite of The Stockades

- issue_template.md
Thanks to @Yehonal for the template
> Create issue template

- src/world/Units/Players/Player.h
Remove forgotten change in https://github.com/AscEmu/AscEmu/commit/5f232465a76961b822a26420f4485bd5249d3bd4
It's not needed anymore since https://github.com/AscEmu/AscEmu/commit/a64ebeabc2bf0c194df5c6c58b9df326a6359d92
Git author didin't work for some reason, author is Zyres
> Remove forgotten change

- src/world/Server/Packets/Handlers/GuildHandler.cpp
Fixes https://github.com/AscEmu/AscEmu/issues/338
> Guild ranks will now update upon rename

- src/world/Management/Battleground/BattlegroundMgr.h
- src/world/Server/Packets/Handlers/CharacterHandler.cpp
- src/world/Server/Script/ScriptMgr.h
- src/world/Server/WorldSession.cpp
- src/world/Server/WorldSession.h
- src/world/Server/WorldSocket.cpp
Added : method HandleDeclinedPlayerNameOpcode
Removed define SCRIPT_MODULE (not used)
Misc Changes
> Added : method HandleDeclinedPlayerNameOpcode

- src/world/Map/MapManagementGlobals.hpp
- src/world/Map/TerrainMgr.cpp
- src/world/Server/WorldSocket.cpp
- src/world/Units/Players/PlayerDefines.hpp
> Updated : NULL -> nullptr

- src/scripts/SpellHandlers/PaladinSpells.cpp
This makes the Guarded by the Light talent refresh the duration of Divine Plea.
Talent - http://wotlk.openwow.com/spell=53585
> Guarded by the Light refreshes Divine Plea

- src/world/Chat/CommandTableStorage.cpp
- src/world/Chat/Commands/LookupCommands.cpp
- src/world/Storage/MySQLDataStore.cpp
> Resolved nullptr crash in .lookup faction command:

- src/world/Objects/Object.cpp
"error: ‘isnan’ was not declared in this scope"
> Fix build on Ubuntu

- sql/world_updates/3_WotLK/2017-10-14_01_shadowfang_keep.sql
- src/scripts/InstanceScripts/Instance_ShadowfangKeep.cpp
- src/scripts/InstanceScripts/Instance_ShadowfangKeep.h
- src/world/Server/Master.cpp
* Arugal intro at entrance
* Prisoner escort events
* Arugal intro at Fenrus death
* All gameobjects handling
* Added missing trash npcs scripts
* Added missing bosses scripts
Signed-off-by: sanctum32 <andriuspel@gmail.com>
> Shadowfang keep rewrite:

- src/world/Management/ItemPrototype.h
- src/world/Server/Packets/Handlers/SpellHandler.cpp
Sorry about the amount of TODO messages in the file, I will handle them soonish.
> Completely rewrite SpellHandler packets and release file under MIT

- src/shared/Threading/AEThread.h
> Fixed linux build

- sql/world_updates/3_WotLK/2017-12-10_01_creature_spawns.sql
- sql/world_updates/4_Cata/2017-12-10_01_creature_spawns.sql
- src/world/Server/Master.cpp
> Remove spawn event The Battle For The Undercity

- src/scripts/LuaEngine/LUAEngine.cpp
before:
after:
test for errors in the script:
everything is working 🍕
> fixed : lua engine load

- src/world/Spell/Spell.Legacy.cpp
- src/world/Spell/Spell.Legacy.h
removed methods:
void SendCastSuccess (target object); 
void SendCastSuccess (const uint64 & guid);
> removed methods SendCastSuccess (target object); & SendCastSuccess (const uint64 & guid);

- src/world/GameCata/Handlers/PetHandler.cpp
- src/world/Server/Packets/Handlers/MovementHandler.cpp
- src/world/Server/Packets/Handlers/PetHandler.cpp
renamed movement_info.orientation -> movement_info.position.o
> Updated method 

- src/world/Management/WeatherMgr.cpp
Notice message about being loaded weather data will displayed in detailed log
> Update loading weather debug message

- src/world/Spell/Spell.Legacy.cpp
Title, more information in comments in the code.
> Core/Spells: Fix aura applying on wotlk and cata builds

- src/world/Objects/Object.cpp
* This limit in cataclysm is not necessary for the Vashj'ir type zones.
> Unnecessary limit in cataclysm.

- src/world/GameCata/Handlers/CharacterHandler.cpp
- src/world/GameClassic/Handlers/CharacterHandler.cpp
- src/world/GameTBC/Handlers/CharacterHandler.cpp
- src/world/GameWotLK/Handlers/CharacterHandler.cpp
- src/world/Spell/Spell.Legacy.cpp
- src/world/Spell/SpellAuras.h
- src/world/Units/Players/PlayerDefines.hpp
Remove stuff I forgot to remove in 0eb5228fa9b01003435b3d84f7fc6ff9f99e8eff
> Verify and implement CharacterScreenFlags

- sql/logon/logon_structure.sql
It gave me an error without that
"Table 'realms' was not locked with LOCK TABLES"
hope that's ok, i'm not an SQL guy
> Fix logon SQL structure

- CMakeLists.txt
Include atomic library with -latomic command
> Fix unix build

- sql/logon/updates/README.md
It tried to apply README.md to logon database, caused std::invalid_argument error and crashed.
Remove readme file also from /location to your compiled ascemu/sql/logon/updates/.
Closes https://github.com/AscEmu/AscEmu/issues/618
> Fix logonserver if experimental filesystem is enabled

- src/world/Server/World.cpp
- src/world/Server/World.h
- src/world/Server/WorldConfig.cpp
- src/world/Server/WorldConfig.h
- src/world/Server/WorldSession.cpp
- src/world/Server/WorldSession.h
- src/world/Server/WorldSocket.cpp
- src/world/Units/Unit.cpp
- Worldsession
- World
- Worldsocket
> Misc cleanup and codestyle

- src/world/Chat/Commands/NpcCommands.cpp
- src/world/Chat/Commands/QuestCommands.cpp
- src/world/Chat/Commands/debugcmds.cpp
- src/world/GameCata/Handlers/LootHandler.cpp
- src/world/GameCata/Handlers/MiscellaneousHandler.cpp
- src/world/Server/Packets/Handlers/MailHandler.cpp
- src/world/Server/Packets/Handlers/MiscHandler.Legacy.cpp
- src/world/Server/WorldSession.h
- src/world/Spell/Spell.Legacy.cpp
- Replace more macros
- Quick fix cata build - need more work (change gold handling in cata to uint64_t)
> Replace more macro calls with wowguid functions. Quick fix cata build.

- src/scripts/InstanceScripts/Instance_ShadowfangKeep.cpp
- src/scripts/LuaEngine/GlobalFunctions.h
- src/scripts/LuaEngine/LUAEngine.cpp
- src/scripts/LuaEngine/LuaGlobal.h
- src/scripts/LuaEngine/UnitFunctions.h
- src/scripts/SpellHandlers/MiscSpells.cpp
- src/scripts/SpellHandlers/QIspells.cpp
- src/world/Chat/Commands/NpcCommands.cpp
- src/world/Chat/Commands/QuestCommands.cpp
- src/world/Chat/Commands/debugcmds.cpp
- src/world/Management/LFG/LFGMgr.cpp
- src/world/Objects/Object.cpp
- src/world/Objects/Object.h
- src/world/Objects/ObjectMgr.cpp
- src/world/Server/Packets/Handlers/GuildHandler.cpp
- src/world/Server/Packets/Handlers/ItemHandler.Legacy.cpp
- src/world/Server/Packets/Handlers/LfgHandler.Legacy.cpp
- src/world/Server/Packets/Handlers/MiscHandler.Legacy.cpp
- src/world/Spell/SpellEffects.Legacy.cpp
- src/world/Units/Players/Player.Legacy.cpp
- src/world/Units/Players/Player.cpp
- Replace last macros call of GET_GUID_LOW and HI
- Remove macros from object.h
> Macro replacement

- src/scripts/EventScripts/Event_Hallows_End.cpp
- src/scripts/GossipScripts/Gossip_Dalaran.cpp
- src/scripts/InstanceScripts/Instance_OldHillsbradFoothills.cpp
- src/scripts/InstanceScripts/Instance_ShadowfangKeep.cpp
- src/scripts/InstanceScripts/Instance_TheShatteredHalls.cpp
- src/scripts/InstanceScripts/Raid_IceCrownCitadel.cpp
- src/scripts/InstanceScripts/Raid_TheEye.cpp
- src/scripts/InstanceScripts/Raid_Ulduar.cpp
- src/scripts/LuaEngine/LUAEngine.cpp
- src/scripts/MapScripts/Northrend/IceCrownCitadel/Icecrown_Citadel.cpp
- src/scripts/MiscScripts/Creatures.cpp
- src/scripts/QuestScripts/Quest_BladeEdge_Mountains.cpp
- src/scripts/QuestScripts/Quest_DeathKnight.cpp
- src/scripts/QuestScripts/Quest_Hellfire_Peninsula.cpp
- src/scripts/QuestScripts/Quest_SholazarBasin.cpp
- src/scripts/SpellHandlers/PetAISpells.cpp
Minor: Add: Prefixing explicit. 
Style: Fix code macro.
> Minor cleaning script code projects 

- sql/world/updates/20181006-00_spell_custom_override.sql
- src/world/Server/Master.cpp
No more 20 million crits with Pyroblast :(
> Spells: Set correct coefficient values for several spells in database

- src/world/GameCata/Storage/DBCStores.cpp
- src/world/GameCata/Storage/DBCStores.h
- src/world/GameCata/Storage/DBCStructures.h
- src/world/GameTBC/Storage/DBCStores.cpp
- src/world/GameTBC/Storage/DBCStores.h
- src/world/GameTBC/Storage/DBCStructures.h
- src/world/GameWotLK/Storage/DBCStores.cpp
- src/world/GameWotLK/Storage/DBCStores.h
- src/world/GameWotLK/Storage/DBCStructures.h
- src/world/Spell/Customization/SpellCustomizations.cpp
- src/world/Spell/Definitions/SpellFailure.h
- src/world/Spell/Spell.Legacy.cpp
- src/world/Spell/Spell.cpp
- src/world/Units/Players/Player.cpp
- src/world/Units/Players/Player.h
Just a small PR to finish area checks
> Spells: Finish area checks in MIT spell cast check function

- src/world/Server/Packets/MsgSetDungeonDifficulty.h
- src/world/Server/Packets/MsgSetRaidDifficulty.h
- src/world/Server/Packets/SmsgInstanceDifficulty.h
This fixes dungeon difficulty and raid difficulties mode switching for WOTLK
> Core/Packets: fixed map difficulties + implemented heroic raid modes

- src/world/Units/Players/Player.Legacy.cpp
Newly created character will get loaded with 100% health and 100% mana, for rogues - 100% energy
> Core/Players: players will get loaded with full health and mana on first login, rogues with full energy

- src/scripts/InstanceScripts/Instance_Arcatraz.cpp
- src/scripts/InstanceScripts/Instance_CullingOfStratholme.cpp
- src/scripts/InstanceScripts/Instance_HallsOfReflection.cpp
- src/scripts/InstanceScripts/Instance_PitOfSaron.cpp
- src/scripts/InstanceScripts/Instance_TheSlavePens.cpp
- src/scripts/InstanceScripts/Raid_BlackTemple.cpp
- src/scripts/InstanceScripts/Raid_IceCrownCitadel.cpp
- src/scripts/InstanceScripts/Raid_Karazhan.cpp
- src/scripts/InstanceScripts/Raid_Magtheridons_Lair.cpp
- src/scripts/InstanceScripts/Raid_Naxxramas.cpp
- src/scripts/InstanceScripts/Raid_Naxxramas.h
- src/scripts/InstanceScripts/Raid_TheEye.cpp
- src/scripts/MiscScripts/City_Dalaran.cpp
- src/scripts/QuestScripts/Quest_BoreanTundra.cpp
- src/scripts/QuestScripts/Quest_ShadowMoon.cpp
- src/scripts/SpellHandlers/QIspells.cpp
- src/world/Management/Battleground/Battleground.cpp
- src/world/Objects/Faction.cpp
- src/world/Spell/SpellAuras.Legacy.cpp
- src/world/Units/Creatures/AIInterface.cpp
- src/world/Units/Creatures/Vehicle.cpp
- src/world/Units/UnitDefines.hpp
UNIT_FLAG_NOT_ATTACKABLE_2 -> UNIT_FLAG_NON_ATTACKABLE
UNIT_FLAG_UNKNOWN_10 -> UNIT_FLAG_IGNORE_PLAYER_NPC
> Renamed and added Unit Flags

- src/tools/ToolsCata/mmaps_generator/MapBuilder.cpp
- src/tools/ToolsClassic/mmaps_generator/MapBuilder.cpp
- src/tools/ToolsMop/mmaps_generator/MapBuilder.cpp
- src/tools/ToolsTBC/mmaps_generator/MapBuilder.cpp
- src/tools/ToolsWotLK/mmaps_generator/MapBuilder.cpp
Signed-off-by: sanctum32 <andriuspel@gmail.com>
> Correction for mmaps generator

- .travis.yml
update dist for .travis
remove macro (WITH_EXPERIMENTAL_FILESYSTEM) https://github.com/AscEmu/AscEmu/commit/d801cbb4249f65f06dbf1673cbfa88e5057287f8
> update dist for .travis and remove macro.

- .travis.yml
> Enable build tools

- src/world/Spell/SpellAuras.Legacy.cpp
- src/world/Spell/SpellEffects.Legacy.cpp
> updated method and style

- .github/issue_template/bug_report.md
- .github/issue_template/feature_request.md
- .github/issue_template/support_request.md
- .github/pull_request_template.md
- .travis.yml
[configuring-issue-templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)
> Update .travis and configuring templates.

- src/scripts/InstanceScripts/Raid_BlackTemple.cpp
- src/scripts/LuaEngine/UnitFunctions.h
- src/scripts/SpellHandlers/LegacyFiles/DeathKnightSpells.cpp
- src/world/AI/MovementAI.cpp
- src/world/Chat/Commands/CharacterCommands.cpp
- src/world/Chat/Commands/DebugCommands.cpp
- src/world/Objects/Object.cpp
- src/world/Server/Packets/Handlers/MovementHandler.cpp
- src/world/Server/Warden/SpeedDetector.cpp
- src/world/Spell/SpellAuras.Legacy.cpp
- src/world/Units/Creatures/AIInterface.cpp
- src/world/Units/Creatures/Creature.cpp
- src/world/Units/Creatures/Pet.cpp
- src/world/Units/Players/Player.Legacy.cpp
- src/world/Units/Players/Player.cpp
- src/world/Units/Unit.Legacy.cpp
- src/world/Units/Unit.cpp
- src/world/Units/Unit.h
With this PR i'm moving speed rate data into separate struct container,
> Core/Unit: implemented a new container for unit speed rates + cleanup

- src/scripts/InstanceScripts/Instance_Deadmines.cpp
- src/scripts/InstanceScripts/Instance_ShadowfangKeep.cpp
- src/scripts/InstanceScripts/Instance_TheSteamvault.cpp
- src/scripts/InstanceScripts/Raid_BlackTemple.cpp
- src/scripts/InstanceScripts/Raid_CoT_BattleOfMountHyjal.cpp
- src/scripts/InstanceScripts/Raid_Karazhan.cpp
- src/scripts/InstanceScripts/Raid_Naxxramas.h
- src/scripts/InstanceScripts/Raid_SerpentshrineCavern.cpp
- src/scripts/SpellHandlers/LegacyFiles/DeathKnightSpells.cpp
- src/shared/LocationVector.h
- src/tools/ToolsCata/vmap_tools/vmap4_extractor/vec3d.h
- src/tools/ToolsMop/vmap_tools/vmap4_extractor/vec3d.h
- src/world/Chat/Commands/debugcmds.cpp
- src/world/Management/TaxiMgr.cpp
- src/world/Management/TransporterHandler.cpp
- src/world/Objects/GameObject.cpp
- src/world/Server/Packets/Handlers/MovementHandler.cpp
- src/world/Server/Warden/SpeedDetector.cpp
- src/world/Spell/SpellEffects.Legacy.cpp
- src/world/Units/Creatures/Pet.cpp
- src/world/Units/Players/PlayerStats.cpp
- src/world/Units/Unit.Legacy.cpp
Use std::sqrt instead of sqrt (just a bit faster)
Build
Tested in-game
> Use std::sqrt instead of sqrt (just a bit faster)

- src/scripts/LuaEngine/UnitFunctions.h
- src/world/Management/Group.cpp
codestyle: UnitFunctions.h
Build
Tested in-game
> codestyle: UnitFunctions.h

- src/scripts/QuestScripts/Unsorted.cpp
https://github.com/AscEmu/OneDB/issues/16 (description of the problem)
Save the chickens🐔
- Build
- Tested in-game
> fix npc id chicken (disabled script)

- src/tools/extras/spellfailure_data/SpellFailure.cpp
1.12.1
SpellCastResult -
PetTameFailure +
2.4.3
SpellCastResult -
PetTameFailure +
3.3.5
SpellCastResult +
PetTameFailure + 
4.3.4
SpellCastResult +
PetTameFailure +
5.4.8
SpellCastResult +
PetTameFailure +
Build
> codestyle: SpellFailure tools.

- .github/workflows/build-test.yml
Migrate from Travis to GitHub Actions (additional test build).
Build
> Migrate from Travis to GitHub Actions (additional test build).

- src/world/Management/Gossip/GossipDefines.hpp
- src/world/Management/Gossip/GossipMenu.cpp
- src/world/Management/QuestMgr.cpp
- src/world/Server/Packets/Handlers/QuestHandler.cpp
- src/world/Server/Packets/SmsgGossipMessage.h
- src/world/Units/Unit.cpp
Quests: Fix player quest log in Wotlk
Quests: Fix quest list for NPCs with multiple quests in TBC
Quests: Do not send gray exclamation mark for quests which player isn't even eligible for
Quests: Minor correction to gossip icons
Gameobjects: Fix gameobject quest givers
Achievements: Fix ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE_TYPE
Packets: Correct SMSG_GOSSIP_MESSAGE format
Closes https://github.com/AscEmu/AscEmu/issues/761
Tested ingame for TBC and wotlk
> Very minor quest fixes

- sql/world/updates/20201012-00_worldstring_tables.sql
- src/world/Chat/Commands/BGCommands.cpp
- src/world/Management/Battleground/Battleground.cpp
- src/world/Management/Battleground/BattlegroundMgr.cpp
- src/world/Management/Gossip/GossipDefines.hpp
- src/world/Management/QuestMgr.cpp
- src/world/Server/Packets/Handlers/AreaTriggerHandler.cpp
- src/world/Server/Packets/Handlers/GuildHandler.cpp
- src/world/Server/Packets/Handlers/NPCHandler.cpp
- src/world/Storage/WorldStrings.h
- src/world/Units/Players/Player.Legacy.cpp
Data is made in the same style
Build
Tested in-game
ps: maybe some values ​​need to be renamed😅😜
> added fields ServerString

- src/world/GameClassic/Storage/DBCStores.cpp
- src/world/GameClassic/Storage/DBCStores.h
disabled some dbc files
Build
Tested in-game
> disabled some dbc files (added to tbc)

- src/shared/WorldPacket.h
- src/world/Management/AuctionHouse.h
- src/world/Map/MapMgr.h
- src/world/Server/Opcodes.hpp
- src/world/Server/WorldConfig.cpp
> Very minor fixes 

- src/scripts/LuaEngine/GlobalFunctions.h
GetClientVersion - client_version
GetAERevision - hash_version
Build
> rewritten function 'GetLuaEngineVersion' now it is 'GetClientVersion'.

- src/tools/ToolsTBC/map_extractor/System.cpp
- src/tools/ToolsWotLK/map_extractor/System.cpp
> versions can be combined (TBC+WOTLK).

- sql/world/updates/20201012-00_worldstring_tables.sql
- src/world/Server/Master.cpp
> add latest world updates

- src/world/Macros/MapsMacros.hpp
- src/world/Map/Map.cpp
- src/world/Map/MapCell.h
- src/world/Map/TerrainMgr.h
- src/world/StdAfx.h
- src/world/Storage/MySQLDataStore.cpp
remove duplicate macro definition
Build
Tested in-game
> remove macros not used and duplicate 

- src/world/Units/Unit.cpp
Transports should always be visible
Also, use viewingDistance from worldmap_info table instead of hardcoded values
Built and tested ingame
> Transport visibility

- sql/world/updates/20201611-00_instance_encounters.sql
- src/shared/CThreads.h
> Fix Mop Build

- src/scripts/GossipScripts/Gossip_Innkeepers.cpp
Updated script. Added all id npc.
Build
Tested in-game
> Update script Gossip Innkeepers 

- src/world/Server/WorldSession.cpp
Opcodes "declension names" are included (Cyrillic BC client)
Build
Tested in-game
> Opcodes "declension names" are included (Cyrillic BC client)

- src/world/Server/Packets/Handlers/MovementHandler.cpp
remove duplicate function
Build
Tested in-game
> remove duplicate function

- sql/world/updates/20210331-00_creature_properties.sql
- src/world/Server/Master.cpp
> CATA remove visible triggers

- src/world/Server/Packets/Handlers/ChatHandler.cpp
Fix raid leader and battleground leader chat in cata
Tested ingame for wotlk and cata
> Small chat fix

- src/configs/world.conf.in
- src/world/Server/Master.cpp
- src/world/Server/WorldConfig.cpp
- src/world/Server/WorldConfig.h
Removed project crashreport (Configs)
**Tests Performed** 
Build
> Removed project crashreport (Configs)

- src/shared/Auth/CMakeLists.txt
- src/shared/CMakeLists.txt
- src/shared/Config/CMakeLists.txt
- src/shared/Database/CMakeLists.txt
- src/shared/Exceptions/CMakeLists.txt
- src/shared/Logging/CMakeLists.txt
- src/shared/Network/CMakeLists.txt
- src/shared/Threading/CMakeLists.txt
- src/shared/Util/CMakeLists.txt
The project shared has now a structure. Sorted files into folders.
> Created structure for shared.

- src/world/Units/Unit.cpp
Spells: Correct energize effect again
> Correct energize effect again

- sql/character/character_base.sql
- sql/logon/logon_base.sql
Update logon and character base sql files
> Update logon and character base sql files

- src/world/Map/MapScriptInterface.h
- src/world/Objects/Transporter.cpp
- src/world/Server/Script/CreatureAIScript.cpp
- src/world/Server/Script/CreatureAIScript.h
- src/world/Server/Script/ScriptMgr.h
- src/world/Units/Creatures/AIInterface.cpp
- src/world/Units/ThreatHandler.cpp
Fixed some Aiinterface script hooks i forgot. Added Some Transport Hooks ( GunshipBattle Preperation ).
> some AIInterface Bugfixes i Noticed.

- .gitignore
- CMakeLists.txt
- dep/g3dlite/FileSystem.cpp
- dep/g3dlite/include/G3D/System.h
- dep/g3dlite/include/G3D/platform.h
- src/logonserver/CMakeLists.txt
- src/logonserver/Realm/RealmManager.hpp
- src/shared/CMakeLists.txt
- src/shared/Common.Legacy.h
- src/shared/Log.cpp
- src/shared/Network/SocketDefines.h
- src/shared/Network/SocketMgrFreeBSD.cpp
- src/shared/Network/SocketMgrFreeBSD.h
- src/shared/Threading/Mutex.cpp
- src/tools/vmap_tools/vmap4_extractor/vmapexport.cpp
- src/world/CMakeLists.txt
- src/world/Map/MapScriptInterface.cpp
- src/world/Units/Creatures/Vehicle.cpp
For now build on freebsd is broken in this PR i plan to get it works again
- [] Build AE.
- [] Server startup.
> [Build] fix FreeBSD build

- src/world/Management/QuestMgr.cpp
Quests: Fix WoWError when trying to accept quest
WoWError was created by who else than me in https://github.com/AscEmu/AscEmu/commit/8005335bb7c86cc7d533304682a575b5255bb148 XD
Closes https://github.com/AscEmu/AscEmu/issues/880
> Fix WoWError when trying to accept quest

- src/scripts/InstanceScripts/Wotlk/Raid_IceCrownCitadel.cpp
- src/scripts/InstanceScripts/Wotlk/Raid_IceCrownCitadel.h
Lord Marrowgar should start the intro when entering the room.
Lady Deathwisper should start the intro when entering the room.
Lady Deathwhisper ADs Spell Timers. (Corrected Timers they get multiplied by 1000 inside the function)
> Icc Small corrections

- src/world/GameCata/Storage/DBCStores.cpp
- src/world/GameCata/Storage/DBCStores.h
- src/world/GameCata/Storage/DBCStructures.h
- src/world/Spell/Spell.cpp
- src/world/Units/Unit.cpp
- src/world/Units/Unit.h
added missing Mount DBCs within its required Spell cast cheks
> Cataclysm Mount DBCs

- src/world/Data/WoWPlayer.hpp
- src/world/Units/Players/Player.Legacy.cpp
- src/world/Units/Players/Player.cpp
- src/world/Units/Players/Player.h
Skills now get recognized by the client, now u can use mounts and other skill related stuff.
currently missing skill bonuses.
> Fixed Cataclysm Skill Update Fields

- src/world/Spell/SpellInfo.cpp
Auras: Implement most of negative auras
> Implement most of negative auras

- sql/world/updates/20210621-00_world_db_version.sql
- src/world/Server/Master.cpp
Now worldserver should start again...
> Fix my mistake in previous world db update file

- src/world/Map/MapScriptInterface.h
- src/world/Units/Creatures/AIInterface.cpp
- src/world/Units/Creatures/AIInterface.h
Creatures assist in fight. Example 5 Mobs in a Group 1 gets attacked, the others also go in Combat. Also added Search assistance on flee if set in ai_agents.
> Added Creature assisting Creatures

- src/world/Spell/SpellAuras.h
> Delete Legacy Aura Handlers

- src/world/Units/Players/Player.Legacy.cpp
> fix warning build C4101

- src/world/Server/WorldSession.cpp
- src/world/Server/WorldSession.h
> inclusion of arenas with TBC

- src/logonserver/Auth/AuthSocket.Legacy.cpp
- src/logonserver/Server/LogonConfig.h
- src/world/GameCata/Storage/DBCStructures.h
- src/world/GameClassic/Storage/DBCStructures.h
- src/world/GameMop/Storage/DBCStructures.h
- src/world/Macros/ScriptMacros.hpp
- src/world/Objects/Object.cpp
- src/world/Units/Players/Player.Legacy.cpp
> code style

- src/logonserver/Auth/AuthSocket.cpp
- src/logonserver/Auth/AuthStructs.h
- src/logonserver/LogonCommServer/LogonCommServer.h
- src/logonserver/Server/IpBanMgr.h
- src/scripts/InstanceScripts/Setup.h
- src/scripts/QuestScripts/Setup.h
- src/shared/RC4Engine.h
- src/world/Chat/Commands/DebugCommands.cpp
- src/world/Management/Charter.hpp
- src/world/Map/MapCell.cpp
- src/world/Map/MapMgr.cpp
- src/world/Movement/Spline/MovementPacketBuilder.cpp
- src/world/Movement/WaypointDefines.h
- src/world/Objects/GameObject.cpp
- src/world/Objects/Transporter.cpp
- src/world/Server/EventableObject.cpp
- src/world/Server/Packets/Handlers/AreaTriggerHandler.cpp
- src/world/Server/Packets/Handlers/ChatHandler.cpp
- src/world/Server/Packets/Handlers/LootHandler.cpp
- src/world/Server/Packets/Handlers/MiscHandler.cpp
- src/world/Server/WorldSession.h
- src/world/Spell/Spell.Legacy.cpp
- src/world/Spell/Spell.cpp
- src/world/Spell/SpellEffects.Legacy.cpp
- src/world/Units/Creatures/AIInterface.cpp
- src/world/Units/Creatures/Creature.cpp
- src/world/Units/Creatures/Pet.cpp
- src/world/Units/Players/Player.Legacy.cpp
- src/world/Units/Unit.Legacy.cpp
- src/world/Units/UnitDefines.hpp
Should fix Unix and Windows non-PCH builds.
Tested on Windows and Ubuntu Server.
Fixes https://github.com/AscEmu/AscEmu/issues/940
> Fix non-PCH builds

- src/scripts/InstanceScripts/CMakeLists.txt
- src/scripts/InstanceScripts/Cata/CMakeLists.txt
- src/scripts/InstanceScripts/Setup.cpp
- src/scripts/InstanceScripts/Setup.h
This adds the cataclysm map ids and cata build information and updates cmake to add cataclysm folders. So i can start dev work on cataclysm.
- [] Server startup.
> Add cataclysm map ids and folder and cmake information for development.

- src/scripts/InstanceScripts/Wotlk/Instance_AhnKahetTheOldKingdom.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_AzjolNerub.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_CullingOfStratholme.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_DrakTharonKeep.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_EyeOfEternity.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_ForgeOfSouls.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_Gundrak.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_HallsOfLightning.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_HallsOfReflection.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_HallsOfStone.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_Nexus.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_PitOfSaron.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_TheOculus.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_TheVioletHold.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_TrialOfTheChampion.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_UtgardeKeep.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_UtgardePinnacle.cpp
- src/scripts/InstanceScripts/Wotlk/Instance_UtgardePinnacle.h
- src/scripts/InstanceScripts/Wotlk/Instance_VaultOfArchavon.cpp
- src/scripts/InstanceScripts/Wotlk/Raid_IceCrownCitadel.cpp
- src/scripts/InstanceScripts/Wotlk/Raid_Naxxramas.cpp
- src/scripts/InstanceScripts/Wotlk/Raid_TheObsidianSanctum.cpp
- src/scripts/InstanceScripts/Wotlk/Raid_TrialOfTheCrusader.cpp
- src/scripts/InstanceScripts/Wotlk/Raid_Ulduar.cpp
This PR is just for the wrath dungeons and raids to enable cells in them. Thanks to @aaron02 for his adding of updating cells in the Magtheridons lair i decided to do them for wrath dungeons and raids. I will open up seperate PR for each expansion.
> Wrath of lich king dungeons and raids cell loading related to #817

- src/scripts/InstanceScripts/Tbc/Raid_GruulsLair.cpp
- src/scripts/InstanceScripts/Tbc/Raid_GruulsLair.h
> Gruuls lair Scripts

- src/scripts/LuaEngine/FunctionTables.h
- src/scripts/LuaEngine/UnitFunctions.h
- src/world/Server/Script/CreatureAIScript.cpp
- src/world/Server/Script/CreatureAIScript.h
- src/world/Units/Creatures/AIInterface.cpp
- src/world/Units/Creatures/AIInterface.h
- src/world/Units/Creatures/Creature.cpp
- src/world/Units/Creatures/Creature.h
Fixed AiUpdate
Added newAIUpdate functionality by Update:: calls instead of events
Fixed Creature Ai Spells not working after a reencounter
Fiexes #816
> Creature AiUpdate Fix

- CMakeLists.txt
- dep/CMakeLists.txt
fix cmake for windows (code style)
removed cmake_policy needs to be revised and it is possible to make a separate file
> fix cmake for windows (code style)

- cmake/Compilers/msvc.cmake
- src/logonserver/Realm/RealmManager.cpp
- src/logonserver/Realm/RealmManager.hpp
- src/logonserver/Server/AccountMgr.cpp
- src/scripts/Battlegrounds/AlteracValley/AlteracValley.cpp
- src/scripts/Battlegrounds/EyeOfTheStorm/EyeOfTheStorm.cpp
- src/scripts/LuaEngine/GameobjectFunctions.cpp
- src/scripts/LuaEngine/ItemFunctions.h
- src/scripts/LuaEngine/UnitFunctions.h
- src/scripts/QuestScripts/Quest_Hellfire_Peninsula.cpp
- src/scripts/SpellHandlers/Scripts/Mage.cpp
- src/shared/Logging/Logger.cpp
- src/tools/mmaps_generator/TerrainBuilder.cpp
- src/tools/vmap_tools/vmap4_extractor/model.cpp
Update Windows default warning level to 4 (if warnings are enabled in CMake)
Fix bunch of level 4 warnings (only 61 warnings left in entire project)
> Update Windows default warning level to 4

- src/world/Units/Creatures/Creature.cpp
- src/world/Units/Creatures/Pet.cpp
- src/world/Units/Players/Player.cpp
- src/world/Units/Summons/Summon.cpp
- src/world/Units/Summons/TotemSummon.cpp
- src/world/Units/ThreatHandler.cpp
Units: Initialize threat manager on first update instead of unit constructor
Fixes threat issue caused by recent changes
> Fix threat issue after recent changes

- src/scripts/Battlegrounds/AlteracValley/AlteracValley.cpp
- src/scripts/LuaEngine/GameobjectFunctions.cpp
- src/scripts/LuaEngine/ItemFunctions.h
- src/scripts/LuaEngine/UnitFunctions.h
- src/world/Management/Group.cpp
- src/world/Management/Group.h
- src/world/Management/ItemPrototype.h
- src/world/Management/LootMgr.cpp
- src/world/Management/LootMgr.h
- src/world/Objects/GameObject.cpp
- src/world/Objects/GameObject.h
- src/world/Objects/Item.cpp
- src/world/Objects/Item.h
- src/world/Objects/Object.cpp
- src/world/Objects/Units/Creatures/Creature.cpp
- src/world/Objects/Units/Creatures/Creature.h
- src/world/Objects/Units/Players/Player.Legacy.cpp
- src/world/Objects/Units/Players/Player.cpp
- src/world/Objects/Units/Players/Player.h
- src/world/Objects/Units/Players/PlayerDefines.hpp
- src/world/Objects/Units/Unit.cpp
- src/world/Server/Packets/Handlers/LootHandler.cpp
- src/world/Server/Packets/Handlers/MiscHandler.cpp
- src/world/Server/Packets/Handlers/TradeHandler.cpp
- src/world/Server/Script/CreatureAIScript.cpp
- src/world/Server/Script/CreatureAIScript.h
- src/world/Server/World.cpp
- src/world/Server/WorldSession.cpp
- src/world/Spell/Spell.cpp
- src/world/Spell/SpellEffects.Legacy.cpp
Rewritten loot System:
Added group round robbin Player.
Added Soulbound tradeable Items.
Fixed Too much Loot droping.
Personal loot.
FFA loot.
Improved loot handling.
Loot gets now Released to other Group Members.
> Loot System Rewrite

- src/world/Management/ObjectMgr.cpp
- src/world/Server/Packets/Handlers/NPCHandler.cpp
- src/world/Server/World.cpp
Creatures: Trainers should check all required spells
Misc: Fix warnings in NPCHandler
> Trainers should check all required spells

- src/world/GameWotLK/Storage/DBCStructures.h
- src/world/Objects/Item.Legacy.cpp
- src/world/Objects/Item.h
- src/world/Objects/Units/Players/Player.Legacy.cpp
- src/world/Objects/Units/Players/Player.cpp
- src/world/Objects/Units/Players/Player.h
Fix Heilroom Item Scaling and Stats Applying
- [] Cata
> Heilroom Scaling Fix

- src/world/Chat/ChannelMgr.cpp
- src/world/Server/Packets/SmsgChannelNotify.h
Channels: Fix city channels bugging out when leaving city and then returning to city
Channels: Use localization for city channels
> Small channel fix

- src/world/Movement/MovementDefines.cpp
- src/world/Objects/MovementDefines.h
- src/world/Objects/MovementInfo.h
- src/world/Objects/Object.cpp
- src/world/Objects/Units/Creatures/Vehicle.cpp
- src/world/Objects/Units/Unit.cpp
- src/world/Server/Packets/Handlers/VehicleHandler.cpp
- src/world/Spell/Spell.cpp
Add accidentally removed stuff back that I removed from PR https://github.com/AscEmu/AscEmu/pull/987. Branch name says it all...
Original author @aaron02 
> Misc: Add accidentally removed stuff back

- src/world/Server/Main.cpp
- src/world/Server/Packets/Handlers/CharacterHandler.cpp
- src/world/Server/WorldSession.cpp
- src/world/Server/WorldSession.h
***Description***
***Todo / Checklist***
***Tests Performed:***
> all code for the class "death knights" will be active with version > TBC

- src/shared/StackWalker.cpp
- src/shared/StackWalker.h
***Description***
***Todo / Checklist***
***Tests Performed:***
> Updated StackWalker

- .github/workflows/build-test.yml
> update workflows to checkout v3

- .gitignore
> Added CLion files to .gitignore.

- src/world/Server/Master.cpp
> Added name localization

- src/world/Chat/ChatHandler.hpp
- src/world/Chat/CommandTableStorage.cpp
- src/world/Chat/Commands/CharacterCommands.cpp
- src/world/Objects/Units/Players/Player.Legacy.cpp
- src/world/Objects/Units/Players/Player.h
- src/world/Objects/Units/Unit.Legacy.cpp
- src/world/Server/Packets/Handlers/MiscHandler.cpp
- src/world/Server/WorldSession.cpp
- src/world/Spell/SpellAuras.Legacy.cpp
- src/world/Spell/Spell_ClassScripts.cpp
the ability to log in and enter the world
can't create a new character
~~crash when exiting the game~~
fix https://github.com/AscEmu/AscEmu/issues/545
✔ Target is branch develop.
✔ Detailed description about this pull request.
✔ Checked AE-Coding standards.
✔ Build AE.
✔ Server startup.
✔ Log into world.
✔ Vanilla
> start of classic version support 🎉

- .github/pull_request_template.md
- README.md
- src/shared/README.md
Update information pull_request_template.md & README.md
> Update information pull_request_template.md & README.md

- src/scripts/Battlegrounds/ArathiBasin/ArathiBasin.cpp
- src/scripts/Battlegrounds/EyeOfTheStorm/EyeOfTheStorm.cpp
- src/scripts/InstanceScripts/Tbc/Raid_Karazhan.cpp
> fix name display on battlefields is now correct

- .circleci/config.yml
- CMakeLists.txt
**Description**: Circleci max supports cmake version 3.16.3
> Circleci max supports cmake version 3.16.3

- sql/world/updates/20220521-00_npc_script_text.sql
- src/scripts/QuestScripts/Quest_TirisfalGlades.cpp
- src/world/Management/QuestMgr.cpp
- src/world/Objects/Units/Players/Player.cpp
- src/world/Server/Master.cpp
- src/world/Server/Script/CreatureAIScript.h
Fix Roguel Deal Quest #504
Added additional Hook to CreatureAIScript
Added Datbase Entry for the Quests Starter and PrevQuest
fix quests displaying wrong #1024
> a rogues deal quest

- sql/world/updates/20220522-00_creature_spawns.sql
- src/world/Server/Master.cpp
deleted double spawn id =134897, 310414, 310662
disabled movement of npc spirit healer
> disabled movement of npc spirit healer

- sql/world/updates/20220524-00_WIP_creature_properties.sql
- sql/world/updates/20220524-00_creature_properties.sql
- src/scripts/QuestScripts/Quest_DeathKnight.cpp
- src/scripts/SpellHandlers/Scripts/Mage.cpp
- src/world/Chat/Commands/debugcmds.cpp
- src/world/GameCata/Storage/DBCStructures.h
- src/world/GameClassic/Storage/DBCStructures.h
- src/world/GameMop/Storage/DBCStructures.h
- src/world/GameTBC/Storage/DBCStructures.h
- src/world/GameWotLK/Storage/DBCStructures.h
- src/world/Map/Maps/MapScriptInterface.h
- src/world/Map/Maps/WorldMap.cpp
- src/world/Server/Master.cpp
- src/world/Server/Script/CreatureAIScript.cpp
- src/world/Server/Script/CreatureAIScript.h
- src/world/Spell/Spell.Legacy.cpp
- src/world/Spell/Spell.Legacy.h
- src/world/Spell/Spell.cpp
- src/world/Spell/SpellEffects.Legacy.cpp
> Deathknight Quests

- src/collision/Maps/TileAssembler.cpp
- src/tools/ToolsCataMop/mmaps_generator/PathGenerator.cpp
- src/tools/ToolsCataMop/vmap_tools/vmap4_assembler/VMapAssembler.cpp
- src/tools/mmaps_generator/PathGenerator.cpp
- src/tools/vmap_tools/vmap4_assembler/VMapAssembler.cpp
Automatically create directories for tools
> Automatically create directories for tools

- src/tools/ToolsCataMop/vmap_tools/vmap4_extractor/vmapexport.cpp
> fix compiling vmaps cata

- cmake/Compilers/msvc.cmake
- src/shared/Common.Legacy.h
Add define NOMINMAX for MSVC compiler
> Add define NOMINMAX for MSVC compiler

- src/world/Objects/Units/Unit.cpp
- src/world/Spell/SpellDefines.hpp
- src/world/Spell/SpellInfo.cpp
- src/world/Spell/SpellInfo.hpp
Auras: Some auras should be stackable from multiple casters
Fixes https://github.com/AscEmu/AscEmu/issues/760
> Some auras should be stackable from multiple casters

- src/world/Objects/Units/Unit.cpp
> fix compilation warnings

- src/scripts/LuaEngine/AuraFunctions.h
- src/scripts/LuaEngine/GameobjectFunctions.cpp
- src/scripts/LuaEngine/GlobalFunctions.h
- src/scripts/LuaEngine/ItemFunctions.h
- src/scripts/LuaEngine/LUAEngine.cpp
- src/scripts/LuaEngine/LUAEngine.h
- src/scripts/LuaEngine/LuaMacros.h
- src/scripts/LuaEngine/SpellFunctions.h
- src/scripts/LuaEngine/UnitFunctions.h
> Remove script macros

- src/tools/ae_tools.sh
- src/world/CMakeLists.txt
- src/world/Objects/Units/Unit.cpp
> visual changes

- src/logonserver/LogonCommServer/LogonCommServer.cpp
- src/shared/Network/ListenSocketWin32.h
- src/shared/Network/Socket.h
- src/shared/Threading/ConditionVariable.h
- src/shared/Threading/LegacyThreadBase.h
- src/shared/Threading/Mutex.h
- src/world/Server/LogonCommClient/LogonCommClient.cpp
> [cmake] using the global version of BUILD_WITH_WARNINGS (enable/disable warnings

- src/world/Chat/CommandTableStorage.cpp
- src/world/Movement/Spline/MovementPacketBuilder.cpp
- src/world/Objects/Units/Players/Player.cpp
> [WotLK] fix register 

- appveyor.yml
Upgrade image to Visual Studio 2022
> [Appveyor] Upgrade image to Visual Studio 2022

- src/world/Chat/Commands/NpcCommands.cpp
- src/world/Chat/Commands/WaypointCommands.cpp
- src/world/Movement/WaypointManager.cpp
- src/world/Movement/WaypointManager.h
- src/world/Objects/Units/Creatures/AIInterface.cpp
- src/world/Objects/Units/Creatures/AIInterface.h
Fixed a Issue Where AIInterface removed the attacker because the Creature is able to be attacked but not hostile.
Fix a the Creature attack part of #1067
Fix Creature Waypoints via Commands #1071
> Fix Combat Issue And Crash on Waypoints

- .github/workflows/build-test.yml
- src/tools/ToolsCataMop/mmaps_generator/MapBuilder.h
- src/tools/mmaps_generator/MapBuilder.h
-  Server startup.
-  Log into world.
-  Classic
-  TBC
-  WotLK
- Cata
> Fix build Mmaps errors when in C++20 mode

- src/world/Chat/Commands/ServerCommands.cpp
- src/world/Server/Console/ConsoleCommands.cpp
- src/world/Server/Packets/Handlers/CharacterHandler.cpp
> visual changes - now information in 2 lines

- src/shared/Common.Legacy.h
- src/tools/ToolsCataMop/map_extractor/System.cpp
> delete macro PLATFORM* - not used

- cmake/Compilers/clang.cmake
- cmake/Compilers/gcc.cmake
- cmake/Systems/Linux.cmake
- cmake/Systems/Windows.cmake
- sql/world/updates/20230301-00_creature_properties.sql
- sql/world/updates/20230301-01_creature_spawns.sql
- src/world/Chat/ChatHandler.cpp
- src/world/Management/AuctionHouse.cpp
- src/world/Objects/Units/Players/Player.cpp
- src/world/Server/Master.cpp
- src/world/Server/Packets/Handlers/ChatHandler.cpp
Removed active triggers they are not used
Increased maximum build id 48107, 12555
Removed std::string LogFileName, bool bLogChat - not used 
Renamed men -> man
-  Classic
- TBC
> Resolved errors in cmake / added comments

- src/world/Server/Master.cpp
adding localization files (locales_creature)
> adding localization files (locales_creature)

- src/world/Server/Packets/Handlers/NPCHandler.cpp
Fix Learning Professions / Spells from Trainers
Fix; #1099 
> Fix Crash on Learning from Trainers

- src/world/Objects/Units/Creatures/AIInterface.cpp
- src/world/Objects/Units/Creatures/AIInterface.h
- src/world/Server/Script/CreatureAIScript.cpp
- src/world/Spell/Spell.cpp
- src/world/Spell/SpellEffects.Legacy.cpp
Added onTaunt ScriptHooks for creature Ai Scripts
todo add onTaunt = 10 to wiki
#1115 
> Creature AI Scripts cleanup and added onTaunt

- src/world/Chat/ChannelMgr.hpp
- src/world/Management/AchievementMgr.h
- src/world/Management/Group.h
- src/world/Map/Area/AreaStorage.hpp
- src/world/Objects/Units/Creatures/Vehicle.hpp
- src/world/Objects/Units/Creatures/VehicleDefines.hpp
- src/world/Objects/Units/Unit.hpp
- src/world/Spell/SpellMgr.hpp
> * Update : namespace C++17

- src/shared/Logging/Logger.cpp
[Fix 831](https://github.com/AscEmu/AscEmu/issues/831)
> add utf8 support messages "Logger" in console.

- src/shared/pchShared.hpp
- src/world/Data/WoWUnit.hpp
- src/world/Objects/Object.hpp
- src/world/Objects/Units/Creatures/Creature.h
- src/world/Objects/Units/Players/Player.hpp
- src/world/Objects/Units/Unit.hpp
- src/world/Server/Packets/Handlers/MailHandler.cpp
- src/world/Spell/Spell.Legacy.cpp
- src/world/Spell/Spell.cpp
- src/world/Spell/SpellAura.cpp
- src/world/Storage/WDB/WDBStructures.hpp
Update : namespace C++17 
Removed extra commas
> Update : namespace C++17 && removed extra commas

- cmake/Modules/FindMySQL.cmake
- src/world/CMakeLists.txt
With this pull request i'm adding basic MariaDB support (also simplified cmake script) and also fixed linking error related to WDB files.
This PR also corrects lualib linking, lualib library will not get linked in world executable if "LUA Engine" is not selected in cmake
- None
- Tested build without "TREAT_WARNINGS_AS_ERRORS" flag turned on in windows and linux (fedora)
- Logged into world
- Compiled with and without LUA engine (MSVC (window 10 x64)/Linux (fedora 38 x64))
> Build fixes

- src/world/Map/Maps/WorldMap.hpp
- src/world/Server/Packets/Handlers/MiscHandler.cpp
This PR fixes potential finite loop crash in "WHO list" opcode handler. I also did minor cleanup
- None
- Compiled AE without "TREAT_WARNINGS_AS_ERRORS" flag turned on.
- Tested ingame (WOTLK)
**Steps to reproduce issue**
- Compile WOTLK version (in debug) and attempt to use /who list, server will freeze and will crash
> Fixed finite loop crash in handleWhoOpcode

- src/tools/ToolsCataMop/map_extractor/System.cpp
- src/tools/ToolsCataMop/mmaps_generator/MapBuilder.cpp
- src/tools/ToolsCataMop/mmaps_generator/MapBuilder.h
- src/tools/ToolsCataMop/mmaps_generator/PathGenerator.cpp
updated for Cata, Mop https://github.com/AscEmu/AscEmu/commit/6169be150c02d4b9fbf4f6f74af95ef34e908713
> Use system available threads for mmaps generation

- src/world/Management/ObjectMgr.cpp
This is minor improvements for achievement reward data loading to minimize errors and corrupted data
- [] Build AE with "TREAT_WARNINGS_AS_ERRORS" flag turned on.
> Improved achievement_rewards data load

- .gitignore
".cache" folder could be generated by ides or extra tools, like clangd
".vscode" folder is created by visual studio code ide, it holds its related content
both folders holds contents which shouldn't be pushed to git repository
- None
- This mainly effects git, it doesn't alters any core functionality
To test this change, simply add .cache or .vscode folders and add any files into these folders, content in these folders should be ignored by git by default (unless you use ```git add --force <path>```). During testing, ensure that .gitignore contains these changes
<!--
This change effects only git, none of existing code is not altered in any way...
> Added extra folders to git ignore list

- src/tools/extras/CMakeLists.txt
CreatureData, SpellData, SpellFailureData <= support for versions up to 3.3.5
> CreatureData, SpellData, SpellFailureData - support for versions up to 3.3.5

- src/world/Objects/Units/Creatures/Creature.cpp
before changes:
after changes:
> Typo fix for logs

- src/world/Chat/CommandTableStorage.cpp
> code style: alignment of rows and columns

- src/shared/Cryptography/MD5.cpp
- src/shared/Cryptography/MD5.h
- src/shared/Cryptography/Sha1.cpp
- src/shared/Cryptography/Sha1.h
fix https://github.com/AscEmu/AscEmu/issues/1170
Need to test for version below version OpenSSL 3.0
> Update Sha1 & MD5 (OpenSSL 3.0)

- dep/README.md
- dep/zlib/ChangeLog
- dep/zlib/FAQ
- dep/zlib/README
- dep/zlib/adler32.c
- dep/zlib/compress.c
- dep/zlib/crc32.c
- dep/zlib/deflate.c
- dep/zlib/deflate.h
- dep/zlib/gzclose.c
- dep/zlib/gzguts.h
- dep/zlib/gzlib.c
- dep/zlib/gzread.c
- dep/zlib/gzwrite.c
- dep/zlib/infback.c
- dep/zlib/inffast.c
- dep/zlib/inffast.h
- dep/zlib/inflate.c
- dep/zlib/inftrees.c
- dep/zlib/inftrees.h
- dep/zlib/trees.c
- dep/zlib/uncompr.c
- dep/zlib/zconf.h
- dep/zlib/zlib.h
- dep/zlib/zutil.c
- dep/zlib/zutil.h
> zlib 1.3.1

- CMakeLists.txt
- cmake/CheckSystem.cmake
- src/logonserver/CMakeLists.txt
- src/tools/ToolsCataMop/map_extractor/CMakeLists.txt
- src/tools/ToolsCataMop/mmaps_generator/CMakeLists.txt
- src/tools/ToolsCataMop/vmap_tools/vmap4_assembler/CMakeLists.txt
- src/tools/ToolsCataMop/vmap_tools/vmap4_extractor/CMakeLists.txt
- src/tools/extras/creature_data/CMakeLists.txt
- src/tools/extras/spell_data/CMakeLists.txt
- src/tools/extras/taxi_path_data/CMakeLists.txt
- src/tools/map_extractor/CMakeLists.txt
- src/tools/mmaps_generator/CMakeLists.txt
- src/tools/vmap_tools/vmap4_assembler/CMakeLists.txt
- src/tools/vmap_tools/vmap4_extractor/CMakeLists.txt
- src/world/CMakeLists.txt
> [CMake] Small cleanup of all CML

- src/world/Server/Packets/SmsgResurrectRequest.h
> fix gcc - compilation error

- CMakeLists.txt
- README.md
- cmake/CheckSystem.cmake
- cmake/Compilers/msvc.cmake
- src/logonserver/CMakeLists.txt
- src/tools/map_extractor/CMakeLists.txt
- src/world/Macros/PetMacros.hpp
cleaning CML.txt (logonserver)
delete macros (PetMacros.hpp)
updated README.md (fixed inactive links)
> cleaning CML.txt & updated README.md

- cmake/Compilers/clang.cmake
- cmake/Compilers/gcc.cmake
- cmake/Modules/FindMySQL.cmake
- src/shared/Database/DatabaseUpdater.cpp
- src/world/Chat/Commands/Account/AccountCommandBan.cpp
- src/world/Chat/Commands/Account/AccountCommandGetId.cpp
- src/world/Chat/Commands/Account/AccountCommandMute.cpp
- src/world/Chat/Commands/Account/AccountCommandUnban.cpp
- src/world/Chat/Commands/Account/AccountCommandUnmute.cpp
- src/world/Chat/Commands/Achievement/AchievementCommandComplete.cpp
Update minimum required versions for gcc and Clang
Fix Clang build
Add support for MariaDB client in Unix
Tested on Debian 12.8 and Ubuntu 24.04
> Fix Clang build

- dep/g3dlite/System.cpp
- dep/g3dlite/include/G3D/AtomicInt32.h
- dep/g3dlite/include/G3D/Matrix3.h
- dep/g3dlite/include/G3D/Ray.h
- dep/g3dlite/include/G3D/System.h
- dep/g3dlite/include/G3D/platform.h
> add support for arm (pack 1)

- .github/workflows/clang-linux-test-x64.yml
> CI: add clang to checklist

- README.md
> CI/Github: Add Clang github actions support. (#1219)

- src/world/Management/TaxiMgr.cpp
Add race specific initial nodes: goblin, worgen, pandaren_alliance, pandaren_horde
> added race specific initial nodes: goblin, worgen, pandaren_alliance, pandaren_horde

- cmake/Modules/AEGitRevision.cmake
- src/shared/git_version.hpp.in
- src/world/Chat/Commands/ServerCommands.cpp
- src/world/Server/Console/ConsoleCommands.cpp
Now in command  you can see which branch you are using.
Active branch
> added new line to command .server info

- CMakeLists.txt
- README.md
> typos corrected

- README.md
> added Badges for macOS
