AscEmu/AscEmu

src/world/Player.cpp

[11:03:46] Sql query failed due to [Duplicate entry '1-1' for key 'PRIMARY'], Query: [INSERT INTO playerpets VALUES('1','1','Raptor','3254','64046','20','80','117440514 0,117440513 0,117440512 0,52472 49408,53582 49408,61676 49408,0 0,100663298 0,100663297 0,100663296 0,','2547','0','0','0','1','1','16','100','8810','824984','1','1')]
The statement "INSERT" produces duplication rates.

Core/Player: Fix to save pet.

---

.travis.yml
cmake/CheckSystem.cmake
cmake/Compilers/clang.cmake
cmake/Requirements.cmake
cmake/Systems/Apple.cmake
cmake/Systems/FreeBSD.cmake
cmake/Systems/Linux.cmake
dep/g3dlite/include/G3D/platform.h
src/logonserver/AuthStructs.h
src/shared/Common.h
src/world/DBC/DBCStores.h

updated travis to use clang instead gcc (to use gcc, just uncomment gcc
lines and comment clang)
base clang requirement is 3.4 version
removed __fastcall redefinition
added addiitonal message that x64 build environment is detected

Added clang support

---

.travis.yml

coverity scan seems to have some issues with clang and gcc must be used. 
Coverity scan tool in travis can't examine needed objects with clang compiler, by searching in google also found results that not only this project has issues with it, so decided to add exception for coverity scan and add gcc/g++ to coverity scan.
Changes:
* formatted travis to 2 space format
* forced gcc usage for coverity scan
* travis will download only 1 commit based git repository (instead of 50) - it reduces git clone time
* removed gcc definitions as project defaults to clang (except for coverity_scan, if still willing to use gcc, just include gcc to compilers list)
* use environment value for compiler version
Also removed additional source repository for gcc 4.8, ubuntu trusty already defaults to gcc 4.8.4

Forced gcc usage for coverity scan

---

appveyor.yml

This service tests msvc builds but firstly you must register project in https://ci.appveyor.com and enable it in github settings to get this configuration working.
Also there is issue with msvc warnings in release mode - I added patch but in different pull request (optimization), so just in case, just set -DBUILD_WITH_WARNINGS=0 to make this working if past pull request wont be merged
Also theres badges for appveyor, you can find links in appveyor project settings (registered project settings)
example:
https://ci.appveyor.com/project/Lectro/ascemu/build/1.0.253 - ignore commit message :)
about messages tab - messages are generated after complete build

Configuration for appveyor

---

src/world/Master.cpp

arcemu-crashdump was renamed quaintly long time ago

Fix crashdumps for Unix systems

---

src/logonserver/Console/LogonConsole.cpp

Commands has been moved to WorldConsole under the name "setaccpermission"

Logon: Remove forgotten line in help section

---

src/world/Units/Creatures/Creature.cpp

This fixes issue where creature corpse delay is set same as for creatures with loot

Fixed creatures with empty loot table corpse decay

---

src/world/Server/Packets/Handlers/ItemHandler.cpp

Players should be able to see on vendor's list, for example mail type items on a priest or rogue, and also items which require reputation or a higher level to equip, but not faction/class/race restricted items.

Players should be able to see all other items on NPC's vendor list expect class, race and faction restricted items

---

src/world/Units/Creatures/Creature.cpp

Anyways this change is quick fix and actually this needs more refactoring since on flags change, AIInterface probably still can hold old value which sets unit to unable to enter to combat fight

Fixed creature script OnDied and instance event OnCreatureDeath events

---

src/scripts/InstanceScripts/Instance_PitOfSaron.cpp
src/scripts/InstanceScripts/Instance_ShadowfangKeep.cpp
src/scripts/InstanceScripts/Instance_TheShatteredHalls.cpp
src/scripts/InstanceScripts/Instance_TheSteamvault.cpp
src/scripts/InstanceScripts/Instance_UtgardeKeep.cpp
src/scripts/InstanceScripts/Raid_BlackTemple.cpp
src/scripts/InstanceScripts/Raid_Magtheridons_Lair.cpp
src/scripts/InstanceScripts/Raid_SerpentshrineCavern.cpp
src/scripts/InstanceScripts/Raid_TheEye.cpp
src/scripts/QuestScripts/Quest_BladeEdge_Mountains.cpp
src/scripts/QuestScripts/Quest_Nagrand.cpp
src/world/Management/Battleground/Battleground.cpp
src/world/Server/Script/CreatureAIScript.cpp
src/world/Spell/SpellTarget.cpp
src/world/Units/Creatures/AIInterface.cpp
src/world/Units/UnitDefines.hpp

These two new flags, when they're set, it stops unit from entering combat with creatures or players
It was tested in violet hold bosses and other creatures which had this flag set.
Signed-off-by: sanctum32 <andriuspel@gmail.com>

Implemented UNIT_FLAG_IGNORE_CREATURE_COMBAT, UNIT_FLAG_IGNORE_PLAYER_COMBAT

---

dep/libmpq/libmpq/mpq_libmpq04.h
src/tools/ToolsWotLK/map_extractor/System.cpp
src/tools/ToolsWotLK/mmaps_generator/MapBuilder.cpp
src/tools/ToolsWotLK/mmaps_generator/PathGenerator.cpp
src/tools/ToolsWotLK/mmaps_generator/TerrainBuilder.cpp
src/tools/ToolsWotLK/vmap_tools/vmap4_extractor/adtfile.cpp
src/tools/ToolsWotLK/vmap_tools/vmap4_extractor/gameobject_extract.cpp
src/tools/ToolsWotLK/vmap_tools/vmap4_extractor/model.cpp
src/tools/ToolsWotLK/vmap_tools/vmap4_extractor/vmapexport.cpp
src/tools/ToolsWotLK/vmap_tools/vmap4_extractor/wmo.cpp
src/world/GameWotLK/Data/MovementInfoWotLK.h
src/world/Objects/Object.h
src/world/Server/Master.cpp
src/world/Server/WorldConfig.cpp
src/world/Spell/SpellCastTargets.cpp
src/world/Units/Players/Player.Legacy.cpp

Ugly casts but required for /wX
Fixes warnings such as:
warning C4800: 'uint32_t': forcing value to bool 'true' or 'false' (performance warning)
warning C4091: 'typedef ': ignored on left of '' when no variable is declared
warning C4996: 'chdir': The POSIX name for this item is deprecated.
etc

Fix Visual Studio build

---

src/world/Data/WoWPlayer.h
src/world/Units/Creatures/Creature.cpp
src/world/Units/Creatures/Creature.h
src/world/Units/Unit.h

- Derived function under Player class had uint16_t variable instead of virtual function's uint32 variable, hence always returning 0 (and later on to be -1) from Unit class.
=> Changed virtual function's, and a derived function's, variables to uint16_t.
- Simplify definitions in WowPlayer.h
This had nothing to do with the data struct changes. This actually was caused accidentally in dd2314f0f26a7d5ec142f037be1d7376f4484138 and 264aa25d5bae8d5969455f6cd821bd457bccc9a9
Partially fixes https://github.com/AscEmu/AscEmu/issues/538

Core/Spells: Fix magical spell damage

---

sql/world/updates/201809XX-XX_creature_properties.sql
src/scripts/Battlegrounds/ArathiBasin.cpp
src/scripts/Battlegrounds/EyeOfTheStorm.cpp
src/scripts/Battlegrounds/IsleOfConquest.cpp
src/scripts/InstanceScripts/Instance_ShadowfangKeep.cpp
src/scripts/LuaEngine/UnitFunctions.h
src/world/Chat/Commands/MiscCommands.cpp
src/world/GameCata/Handlers/LootHandler.cpp
src/world/Map/MapMgr.cpp
src/world/Objects/Faction.cpp
src/world/Objects/GameObject.cpp
src/world/Objects/GameObject.h
src/world/Server/Packets/Handlers/MiscHandler.Legacy.cpp
src/world/Server/Packets/Handlers/NPCHandler.cpp
src/world/Spell/Definitions/AuraEffects.h
src/world/Spell/Spell.Legacy.cpp
src/world/Spell/SpellAuras.Legacy.cpp
src/world/Spell/SpellAuras.h
src/world/Spell/SpellEffects.Legacy.cpp
src/world/Units/Creatures/AIInterface.cpp
src/world/Units/Creatures/Creature.cpp
src/world/Units/Creatures/Creature.h
src/world/Units/Players/Player.Legacy.cpp
src/world/Units/Players/Player.cpp
src/world/Units/Players/Player.h
src/world/Units/Unit.Legacy.cpp
src/world/Units/Unit.cpp
src/world/Units/Unit.h
src/world/Units/UnitDefines.hpp

More stuff from my old work:
- Rewrite stealth and invisibility detection
- Correct parameter for trap objects
- Unset invisibility types for creatures in database
- Correct line endings in Player.cpp and Player.h
- Fix random crash in legacy spell system
The creatures which had invisiblity type set have now proper passive aura set.
Only creatures with invisibility type 15 are left. These are trigger or placeholder npcs and should never be seen by players.
Closes https://github.com/AscEmu/AscEmu/issues/104

Rewrite stealth and invisibility

---

src/world/Objects/Object.cpp
src/world/Spell/Spell.Legacy.cpp
src/world/Units/Players/Player.cpp
src/world/Units/Players/Player.h
src/world/Units/Unit.cpp
src/world/Units/Unit.h

Fix https://github.com/AscEmu/AscEmu/issues/649 properly:
Spell casting should always reset attack timers if spell is not instant cast and has not special attribute preventing the reset.
Also fix some typos in comments.

Spells: Correctly reset attack timers instead of delaying on spell cast

---

src/world/Spell/Customization/HackFixes.cpp
src/world/Spell/Customization/SpellCustomizations.cpp
src/world/Spell/Spell.Legacy.cpp
src/world/Spell/Spell.Legacy.h
src/world/Spell/Spell.cpp
src/world/Spell/SpellDefines.hpp
src/world/Spell/SpellEffects.Legacy.cpp
src/world/Units/Players/Player.cpp
src/world/Units/Unit.cpp

- More spell target checks
- Some spell definitions cleaned up
- Fix some warnings in MIT files (conversion from int to uint8_t, possible loss of data...)

MIT Spell::canCast() part 4

---

src/world/Server/Script/CreatureAIScript.h
src/world/Server/Script/ScriptMgr.h

This will reduce amount of scripts where you may need to split into constructor to access specific script data. For example, you have script_A.cpp, script_B.cpp and you need to access data from script_A.cpp in script_B.cpp. You can do such tasks by splitting their script into constructor or using extern keyword. These new functions are scriptable and could be called from any script without splitting into constructor and similar. This will reduce amounts of c++ class casts or c++ constructoring in headers

Core/Scripts: added new scriptable virtual functions for easer data sharing between scripts

---

cmake/CheckSystem.cmake

Cmake oftenly fails to detect Win64 prefix. This will give more occurate result

Improved x64 bit system detection in cmake

---

src/world/Units/Creatures/Creature.cpp

>test : .npc spawn 28312
> console : Sql query failed due to [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1], Query: [INSERT INTO creature_spawns VALUES(316809,12340,12340,28312,0,1676.62,1677.2,121.67,0,0,25292,35,0,50331648,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,)]

Fix syntax sql.

---

src/world/Management/AchievementMgr.cpp
src/world/Management/AchievementMgr.h

- Drop typedefs for uint8, uint16, uint32, uint64...... use uint8_t, uint16_t, uint32_t, ....
- Drop NULL use nullptr
test case:
.achieve complete 156
...
.achieve reset 156

update AchievementMgr for modern c ++

---

src/collision/BoundingIntervalHierarchy.cpp
src/shared/Common.Legacy.h
src/tools/ToolsCata/vmap_tools/vmap4_extractor/adtfile.cpp
src/tools/ToolsClassic/vmap_tools/vmap4_extractor/adtfile.cpp
src/tools/ToolsMop/vmap_tools/vmap4_extractor/adtfile.cpp
src/tools/ToolsTBC/vmap_tools/vmap4_extractor/adtfile.cpp
src/tools/ToolsWotLK/vmap_tools/vmap4_extractor/adtfile.cpp

workarounds that are no longer needed since Visual C++ 2015 to use C99 conformant functions..

Removes some decades-old Visual C++ 

---

cmake/Compilers/msvc.cmake
cmake/Options.cmake

Some dependencies for example maybe aren't updated to recent C++ standarts. With this option we can temporally enable/disable warnings treatment as errors

Core/Build: implemented new cmake option "TREAT_WARNINGS_AS_ERRORS".

---

src/world/Server/Script/ScriptMgr.cpp
src/world/Server/Script/ScriptMgr.h
src/world/Spell/Spell.Legacy.cpp
src/world/Spell/SpellScript.h

"beforeSpellEffect" - script event is executed before spell handler, it also can prevent default spell effect "afterSpellEffect" - event called after spell effect handling

Script/Spells: implemented new scriptable events

---

src/world/Units/Unit.Legacy.cpp

after death, speed normalizes [#749]
Build
Tested in-game (wotlk).

fix: after death, speed normalizes.

---

src/scripts/SpellHandlers/LegacyFiles/ItemSpells_1.cpp
src/shared/Database/MySQLDatabase.cpp

Fix unix build
Also, 'my_bool' was removed in MySQL 8.0.1 https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling

Fix unix build

---

src/world/Server/WorldRunnable.cpp
src/world/Server/WorldRunnable.h

Diff was always null in WorldRunnable thread because Util::getMSTime() - Util::getMSTime() = 0 ;)
Fixes https://github.com/AscEmu/AscEmu/issues/813
Built and tested

Threading: Fix diff in WorldRunnable thread

---

src/scripts/SpellHandlers/Scripts/Druid.cpp
src/scripts/SpellHandlers/Scripts/Mage.cpp
src/scripts/SpellHandlers/Scripts/Paladin.cpp
src/scripts/SpellHandlers/Scripts/Priest.cpp
src/scripts/SpellHandlers/Scripts/Rogue.cpp
src/scripts/SpellHandlers/Scripts/Shaman.cpp
src/world/Spell/Spell_ClassScripts.cpp

**Todo / Checklist:**
- Spells adjusted for versions, Classic, TBC, WolTK & Cata
src/scripts/SpellHandlers/Scripts/Druid.cpp
src/scripts/SpellHandlers/Scripts/Mage.cpp
src/scripts/SpellHandlers/Scripts/Paladin.cpp
src/scripts/SpellHandlers/Scripts/Priest.cpp 
src/scripts/SpellHandlers/Scripts/Rogue.cpp
src/scripts/SpellHandlers/Scripts/Shaman.cpp
src/world/Spell/Spell_ClassScripts.cpp
- Build
Classic, TBC, WolTK & Cata
- Tested in-gam
Classic, TBC, WolTK & Cata

Spells have been adjusted, to eliminate charging errors.

---

src/world/Chat/Commands/MiscCommands.cpp
src/world/GameCata/Storage/DBCStructures.h
src/world/GameClassic/Storage/DBCStructures.h
src/world/GameMop/Storage/DBCStructures.h
src/world/GameTBC/Storage/DBCStructures.h
src/world/GameWotLK/Storage/DBCStructures.h
src/world/Storage/DB2/DB2Loader.h
src/world/Storage/DB2/DB2Structures.h
src/world/Storage/DBC/DBCGlobals.hpp
src/world/Storage/DBC/DBCLoader.cpp
src/world/Storage/DBC/DBCLoader.hpp
src/world/Storage/DBC/DBCRecord.cpp
src/world/Storage/DBC/DBCRecord.hpp
src/world/Storage/DBC/DBCSQL.cpp
src/world/Storage/DBC/DBCSQL.hpp
src/world/Storage/DBC/DBCStorage.hpp

MOP Updated structure for ChrClasses.dbc and ChrRaces.dbc
MOP Updated structure for CurrencyTypes.dbc
MOP Updated structure for SkillLine.dbc
MOP Updated structure for SpellRadius.dbc
MOP Updated structure for SpellRuneCost.dbc
MOP Updated structure for TaxiNodes.dbc WMOAreaTable.dbc Faction.dbc
MOP Updated structure for AreaTrigger.dbc and ScalingStatValues.dbc
MOP Updated structure for DungeonEncounter.dbc
MOP Updated structure for Vehicle.dbc
Drop typedefs for uint8, int32, uint32
Update : namespace C++17
Code style and equal tab/..
Build

MOP Updated structure for .dbc

---

src/world/Server/Packets/CmsgMessageChat.h
src/world/Server/Packets/Handlers/LootHandler.cpp
src/world/Server/Packets/SmsgLootMoneyNotify.h
src/world/Server/World.cpp
src/world/Units/Creatures/AIInterface.cpp
src/world/Units/Creatures/Creature.cpp
src/world/Units/Unit.Legacy.cpp

Fix SMSG_MESSAGECHAT in several places where the packet is sent (slightly related to https://github.com/AscEmu/AscEmu/issues/854)
Fix party leader and battleground chat in <= WotLK
Fix text emotes and yelling in >= Cata
Correct SMSG_LOOT_MONEY_NOTIFY packet structure
Built and tested ingame in wotlk and cata

Some chat fixes

---

src/logonserver/Console/LogonConsole.cpp
src/logonserver/LogonCommServer/LogonCommServer.cpp
src/logonserver/LogonStdAfx.h
src/logonserver/Server/AccountMgr.cpp
src/logonserver/Server/Master.cpp
src/shared/CMakeLists.txt
src/shared/Util.cpp
src/shared/Util.hpp
src/shared/Util/Strings.cpp
src/shared/Util/Strings.hpp
src/world/Chat/Commands/CharacterCommands.cpp
src/world/Chat/Commands/LookupCommands.cpp
src/world/Chat/Commands/RecallCommands.cpp
src/world/Management/AuctionHouse.cpp
src/world/Management/ChannelMgr.cpp
src/world/Management/Guild/GuildMgr.cpp
src/world/Management/Item.Legacy.cpp
src/world/Management/QuestMgr.cpp
src/world/Map/InstanceMgr.cpp
src/world/Objects/ObjectMgr.cpp
src/world/Server/LogonCommClient/LogonCommHandler.cpp
src/world/Server/Packets/Handlers/CharacterHandler.cpp
src/world/Server/Packets/SmsgMonsterMoveTransport.h
src/world/StdAfx.h
src/world/Storage/MySQLDataStore.cpp
src/world/Units/Creatures/Corpse.cpp
src/world/Units/Players/Player.Legacy.cpp

Created Strings.hpp/cpp to encapsulate string utils from class Util. So we dont need any pre-/infix in methods name, because of the new namespace.

Encapsulate string utils in class Util

---

src/shared/Logging/Logger.cpp

Logger::setMinimumMessageType no Crash with MessageType Trace anymore.

Bugfix: Logger::setMinimumMessageType no Crash with MessageType Trace.

---

src/logonserver/CMakeLists.txt
src/logonserver/Realm/CMakeLists.txt
src/logonserver/Realm/RealmFlag.hpp
src/logonserver/Server/LogonServerDefines.hpp
src/logonserver/Server/RealmsMgr.cpp

The RealmFlags are now a custom file named RealmFlag.hpp. The Prefix REALM_FLAG was removed and the enum is now in the namespave AscEmu::Realm. The RealmFlag REALM_FLAG_SPCIFYBUILD was renamed to SPECIFIC_BUILD.

Encapsulate RealmFlags from LogonServerDefines to RealmFlag.

---

src/world/Spell/Spell.cpp

Spells: Remove unimplemented object types from open lock cast check
Closes https://github.com/AscEmu/AscEmu/issues/876

Spells: Remove unimplemented object types from open lock cast check

---

CMakeLists.txt
cmake/Systems/Apple.cmake
cmake/Systems/FreeBSD.cmake
cmake/Systems/Linux.cmake
src/shared/Database/DatabaseUpdater.cpp

Automatic database update feature applies SQL updates in random order and messes up entire database in Linux.
std::filesystem::recursive_directory_iterator doesn't get files in sorted order in Linux while in Windows they seem to be always sorted.
Cppreference says "The iteration order is unspecified, except that each directory entry is visited only once."
Before:
After:

Fix database automatic update in Linux

---

src/tools/vmap_tools/vmaps.sh

The vmaps.sh script is refering to binary names that don't exist.
Binaries produced by the build are called: `vmap4_extractor` and `vmap4_assembler`.
- [] Server startup.

correct binary names inside vmaps.sh script

---

src/tools/map_extractor/System.cpp

Building the tools on Linux systems fails with:
```
/home/eric/projects/ascemu/server/src/tools/map_extractor/System.cpp: In function ‘std::string getWowExeName()’:
/home/eric/projects/ascemu/server/src/tools/map_extractor/System.cpp:75:18: error: ‘transform’ is not a member of ‘std’
75 |             std::transform(name.begin(), name.end(), name.begin(), [](unsigned char chars) { return std::tolower(chars); });
|                  ^~~~~~~~~
make[2]: *** [src/tools/map_extractor/CMakeFiles/map_extractor.dir/build.make:76: src/tools/map_extractor/CMakeFiles/map_extractor.dir/System.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1057: src/tools/map_extractor/CMakeFiles/map_extractor.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
This PR adds the required …

Fix BUILD_TOOLS on Linux systems

---

src/world/Management/QuestDefines.hpp
src/world/Management/TransporterHandler.cpp
src/world/Objects/MovementDefines.h
src/world/Objects/Object.cpp
src/world/Objects/Transporter.cpp
src/world/Server/Packets/Handlers/QueryHandler.cpp
src/world/Server/Packets/Handlers/QuestHandler.cpp
src/world/Server/Packets/Handlers/VehicleHandler.cpp
src/world/Server/Packets/SmsgCharEnum.h
src/world/Server/Packets/SmsgFeatureSystemStatus.h
src/world/Server/Packets/SmsgQuestgiverStatus.h
src/world/Server/Packets/SmsgQuestgiverStatusMultiple.h
src/world/Server/Packets/SmsgSetFlatSpellModifier.h
src/world/Server/Packets/SmsgSetPctSpellModifier.h
src/world/Spell/SpellAuras.Legacy.cpp
src/world/Units/Players/Player.cpp
src/world/Units/Players/Player.h
src/world/Units/Unit.cpp

Spells: Correct spell modifier packets in Cata
Quests: Correct quest packets and quest status in Cata
Misc: Fix level 4 warnings in Cata
Closes https://github.com/AscEmu/AscEmu/issues/896

Fix spell modifier packets in Cata

---

src/world/Storage/MySQLDataStore.cpp

> 23:53:01 [INFO]: MySQLDataLoads : Loaded 800 rows from player_classlevelstats table in 12 ms!
> 23:53:01 [ERROR][MAJOR]: Server has crashed. Creating crash dump file CrashDumps\dump-world.exe.dmp
> 23:53:01 [ERROR][MAJOR]: Crash Handler : Advanced crash handler initialized.
> 23:53:06 [INFO]: sql : Waiting for all database queries to finish...
> 23:53:07 [INFO]: sql : All pending database operations cleared.
> 23:53:07 [INFO]: Saving all players to database...
> 

fix crash 🐐

---

src/world/Management/LFG/LFGMgr.cpp

Fixes #927. Groups can now queue and search for more players.

Fix group dungeon finder

---

src/scripts/InstanceScripts/Tbc/Instance_Arcatraz.cpp
src/scripts/InstanceScripts/Tbc/Instance_AuchenaiCrypts.cpp
src/scripts/InstanceScripts/Tbc/Instance_BlackMorass.cpp
src/scripts/InstanceScripts/Tbc/Instance_BloodFurnace.cpp
src/scripts/InstanceScripts/Tbc/Instance_Botanica.cpp
src/scripts/InstanceScripts/Tbc/Instance_HellfireRamparts.cpp
src/scripts/InstanceScripts/Tbc/Instance_MagistersTerrace.cpp
src/scripts/InstanceScripts/Tbc/Instance_ManaTombs.cpp
src/scripts/InstanceScripts/Tbc/Instance_OldHillsbradFoothills.cpp
src/scripts/InstanceScripts/Tbc/Instance_SethekkHalls.cpp
src/scripts/InstanceScripts/Tbc/Instance_ShadowLabyrinth.cpp
src/scripts/InstanceScripts/Tbc/Instance_TheMechanar.cpp
src/scripts/InstanceScripts/Tbc/Instance_TheShatteredHalls.cpp
src/scripts/InstanceScripts/Tbc/Instance_TheSlavePens.cpp
src/scripts/InstanceScripts/Tbc/Instance_TheSteamvault.cpp
src/scripts/InstanceScripts/Tbc/Instance_TheUnderbog.cpp
src/scripts/InstanceScripts/Tbc/Raid_BlackTemple.cpp
src/scripts/InstanceScripts/Tbc/Raid_CoT_BattleOfMountHyjal.cpp
src/scripts/InstanceScripts/Tbc/Raid_Karazhan.cpp
src/scripts/InstanceScripts/Tbc/Raid_SunwellPlateau.cpp
src/scripts/InstanceScripts/Tbc/Raid_TheEye.cpp
src/scripts/InstanceScripts/Tbc/Raid_ZulAman.cpp

This adds cell loading to all tbc dungeons and raids except for Gruuls Lair,  Magtheridon's lair and Serpentshrine Caverns as @aaron02 has did this already or is planning to.

Instance cell loading for TBC dungeons/raids

---

src/world/Chat/Commands/NpcCommands.cpp
src/world/Spell/Spell.Legacy.h
src/world/Spell/Spell.cpp
src/world/Spell/SpellAuras.cpp
src/world/Spell/SpellInfo.cpp
src/world/Spell/SpellInfo.hpp
src/world/Spell/SpellTarget.Legacy.cpp

Chat: Fix crash in npc respawn command
Spells: Fix some caster/target issues when spell is triggered by an aura
Spells: Check for explicit targets in ::canCast()

Spell explicit target

---

src/scripts/InstanceScripts/Tbc/Raid_GruulsLair.cpp
src/scripts/InstanceScripts/Tbc/Raid_Magtheridons_Lair.cpp
src/scripts/InstanceScripts/Wotlk/Instance_TheVioletHold.cpp
src/world/Management/ArenaTeam.cpp
src/world/Management/Item.Legacy.cpp
src/world/Map/MapMgr.cpp
src/world/Server/Packets/SmsgMessageChat.h
src/world/Server/Script/CreatureAIScript.h
src/world/Server/Script/ScriptMgr.h
src/world/Units/Creatures/AIInterface.cpp
src/world/Units/Players/Player.cpp
src/world/Units/Unit.Legacy.cpp
src/world/Units/UnitDefines.hpp

Players: Fix issue where health or mana sometimes ends up being uint32_t(-1)
Units: Small refactoring to melee attack packets, should now show absorbs correctly
Misc: Fix bunch of level 4 warnings (the rest are for you @Zyres 😉 )

Fix player health issue, absorbs in melee attack packet and couple warnings

---

src/world/Units/Creatures/AIInterface.cpp

This fixes 2 warnings during compiling AIInterface.cpp(3528): warning C4018: '<': signed/unsigned mismatch)

Fix missed warnings when compiling

---

src/world/Server/Packets/Handlers/ItemHandler.cpp
src/world/Server/Packets/Handlers/NPCHandler.cpp
src/world/Server/Packets/Handlers/SkillHandler.cpp
src/world/Spell/Spell.cpp
src/world/Spell/SpellEffects.Legacy.cpp
src/world/Spell/SpellInfo.cpp
src/world/Units/Creatures/AIInterface.cpp
src/world/Units/Creatures/Pet.cpp
src/world/Units/Players/Player.Legacy.cpp
src/world/Units/Players/Player.cpp
src/world/Units/Players/Player.h
src/world/Units/Unit.Legacy.cpp

Players: Initialize profession points properly
Spells: Do not check for explicit target when spell is targeting pet
Items: Show correct itemset when querying items
Closes https://github.com/AscEmu/AscEmu/issues/908
NOTE: this will NOT fix existing characters. If you want your existing character to be able to learn professions please run following SQL query to characters database:
`
UPDATE characters SET available_prof_points='2' WHERE available_prof_points='0';
`

Initialize profession points properly

---

src/world/Chat/Commands/NpcCommands.cpp
src/world/Data/Flags.hpp
src/world/Macros/CreatureMacros.hpp
src/world/Management/Skill.hpp
src/world/Objects/ObjectMgr.cpp
src/world/Objects/ObjectMgr.h
src/world/Server/Packets/Handlers/NPCHandler.cpp
src/world/Server/World.cpp
src/world/Server/WorldSession.h
src/world/Spell/SpellMgr.cpp
src/world/Spell/SpellMgr.hpp
src/world/Units/Players/Player.Legacy.cpp
src/world/Units/Players/Player.cpp
src/world/Units/Players/Player.h
src/world/Units/Unit.h

NPCs: Improve class and profession trainers, now cata uses same code for trainer spells as wotlk
NPCs: Trainers can teach you multiple spells now (Cata)
Skills: Profession skill levels should show correctly on trainers now (Cata)
Skills: Fix missing unlearn button in professions under skill tab (Classic - wotlk)
Skills: Fix already learnt profession ranks appearing in trainer list (Classic - wotlk)
Closes https://github.com/AscEmu/AscEmu/issues/752 and https://github.com/AscEmu/AscEmu/issues/28
TODO: when a skill is changed, added or removed we loop through all skills and update each and every skill. This generates some weird skill gain messages to chat. In the future, if we need to update, add or remove a skill we should only update that WoWData field instead of looping …

Improve profession and class trainers

---

sql/world/updates/20211112-00_playercreateinfo_spell_learn.sql
src/scripts/SpellHandlers/Scripts/Mage.cpp
src/world/Objects/Object.cpp
src/world/Server/Master.cpp
src/world/Spell/SpellInfo.cpp
src/world/Units/Unit.Legacy.cpp
src/world/Units/Unit.cpp

Units: Fix issue where mobs sometimes are not lootable
Spells: Prevent negative spell damage when spell damage is scaling with level
Spells: Correct some player starting spells
Spells: Correct two mage passive spells in Cata
- [] BC

Couple spell fixes and fixing npc loot issue

---

src/world/Units/Unit.cpp

Spells: Fix issue where player cannot attack mobs after a stun aura has been removed
Closes https://github.com/AscEmu/AscEmu/issues/966 and https://github.com/AscEmu/AscEmu/issues/959

Fix issue where player cannot attack mobs after being stunned

---

sql/character/updates/20220116-00_characters.sql
src/scripts/LuaEngine/UnitFunctions.h
src/scripts/SpellHandlers/LegacyFiles/MiscSpells.cpp
src/world/Management/AchievementMgr.cpp
src/world/Management/AchievementMgr.h
src/world/Objects/Units/Players/Player.Legacy.cpp
src/world/Objects/Units/Players/Player.cpp
src/world/Objects/Units/Players/Player.h
src/world/Server/Master.cpp
src/world/Server/Packets/Handlers/NPCHandler.cpp
src/world/Spell/Spell.Legacy.cpp
src/world/Spell/Spell.Legacy.h
src/world/Spell/SpellEffects.Legacy.cpp

Scripts: Call achievement criteria scripts after requirements have been checked
This fixes crash when npc casts any spell
Players: Correct home bind position, should also have orientation in it
Source: https://www.reddit.com/r/classicwow/comments/s07wfl/old_school_tricks_the_direction_you_face_when_you/

Bind point and achievement crash fix

---

src/world/Objects/Units/Unit.cpp
src/world/Objects/Units/Unit.h
src/world/Spell/SpellAuras.Legacy.cpp
src/world/Spell/SpellAuras.h
src/world/Spell/SpellDefines.hpp

Auras: Passive auras with effect 262 must be sent to client
This fixes spells like warrior talent Juggernaut which makes Charge useable in combat

Passive auras with effect 262 must be sent to client

---

src/world/Objects/Units/Unit.cpp
src/world/Spell/SpellAuras.cpp
src/world/Spell/SpellAuras.h

Auras: Correct reapply mechanism on stackable auras
Atm there is a bug with stackable auras on aura reapply (which I introduced :P). When old effect is removed it only removed base amount and ignored possible aura stacks.

Correct reapply mechanism on stackable auras

---

cmake/Compilers/gcc.cmake
src/logonserver/CMakeLists.txt
src/shared/CMakeLists.txt
src/shared/Common.hpp.in
src/world/CMakeLists.txt

Using the types and functions in <filesystem> does not require linking with -lstdc++fs now.

Using the types and functions in <filesystem> does not require linking with -lstdc++fs now.

---

sql/world/updates/20220611-00_spawns.sql
src/world/Server/Master.cpp

Fix spawns in Death Knight starting place for cata and mop. They are same in wotlk - mop.
Fixes https://github.com/AscEmu/AscEmu/issues/1030

Fix spawns in Death Knight starting place for cata and mop

---

dep/StormLib/CMakeLists.txt

Disable options StormLib, for the extractor, these functions are not needed (only cata+)

Disable options StormLib

---

cmake/Modules/FindOpenSSL.cmake
dep/openssl/CMakeLists.txt

**Needs to be updated (OpenSSL 3.0):**
```C++
MD5.cpp(35,5): warning C4996: 'MD5_Update': Since OpenSSL 3.0
MD5.cpp(40,5): warning C4996: 'MD5_Final': Since OpenSSL 3.0
MD5.cpp(45,5): warning C4996: 'MD5_Init': Since OpenSSL 3.0
Sha1.cpp(26,5): warning C4996: 'SHA1_Init': Since OpenSSL 3.0
Sha1.cpp(31,5): warning C4996: 'SHA1_Update': Since OpenSSL 3.0
Sha1.cpp(61,5): warning C4996: 'SHA1_Final': Since OpenSSL 3.0
WowCrypt.cpp(77,5): warning C4996: 'RC4_set_key': Since OpenSSL 3.0
WowCrypt.cpp(79,5): warning C4996: 'RC4': Since OpenSSL 3.0
```
There is a question: should .lib be copied automatically (in this mode). how is it now? 🤔
in this case everything is fine 😁

Support for OpenSSL 3.0

---

.gitignore
src/logonserver/CMakeLists.txt
src/logonserver/Console/LogonConsole.cpp
src/logonserver/LogonConf.hpp.in
src/logonserver/Server/LogonConfig.cpp
src/logonserver/Server/Master.cpp
src/shared/AEVersion.hpp.in
src/shared/CMakeLists.txt
src/shared/README.md
src/tools/ToolsCataMop/map_extractor/CMakeLists.txt
src/tools/ToolsCataMop/map_extractor/System.cpp
src/tools/ToolsCataMop/vmap_tools/vmap4_extractor/CMakeLists.txt
src/tools/ToolsCataMop/vmap_tools/vmap4_extractor/vmapexport.cpp
src/tools/map_extractor/CMakeLists.txt
src/tools/map_extractor/System.cpp
src/tools/vmap_tools/vmap4_extractor/CMakeLists.txt
src/tools/vmap_tools/vmap4_extractor/modelheaders.h
src/tools/vmap_tools/vmap4_extractor/vmapexport.cpp
src/world/WorldConf.h.in

Misc: Move VERSION_STRING to shared project from world
Logon: Logonserver properly includes VERSION_STRING now. It used to be undefined.
Extractors: Fix VMaps extractor for classic and TBC, and possibly for mop too
Classic and TBC have some extra fields in model headers. Mop/cata extractor has now access to VERSION_STRING as well.
TBC extractor had been broken since 2020 XD (https://github.com/AscEmu/AscEmu/commit/293d0a737c4d10c1c40aea4b00609bbc35de4391)
Closes https://github.com/AscEmu/AscEmu/issues/1065

Fix TBC vmaps extractor

---

src/scripts/InstanceScripts/Tbc/CoilfangReservoir/SerpentShrine/Raid_SerpentshrineCavern.cpp
src/world/Chat/Commands/DebugCommands.cpp
src/world/Chat/Commands/NpcCommands.cpp
src/world/Data/WoWUnit.hpp
src/world/Management/GameEvent.cpp
src/world/Map/Maps/MapScriptInterface.cpp
src/world/Objects/ItemDefines.hpp
src/world/Objects/Transporter.cpp
src/world/Objects/Units/Creatures/AIInterface.cpp
src/world/Objects/Units/Creatures/Creature.cpp
src/world/Objects/Units/Creatures/Creature.h
src/world/Objects/Units/Creatures/Summons/Summon.cpp
src/world/Objects/Units/Players/Player.cpp
src/world/Objects/Units/Unit.cpp
src/world/Objects/Units/Unit.hpp
src/world/Server/Script/CreatureAIScript.cpp
src/world/Server/WorldSession.cpp
src/world/Spell/Spell.cpp
src/world/Spell/SpellAuras.Legacy.cpp
src/world/Storage/MySQLDataStore.cpp
src/world/Storage/MySQLDataStore.hpp
src/world/Storage/MySQLStructures.h

Creatures: Fix an issue where some NPC equipments are not showing correctly in TBC (thanks for the help @Zyres 😃 )
Creatures: Implement dual wield and offhand attacks for creatures
Summons: Fix an issue when summoned unit is unsummoned
Closes https://github.com/AscEmu/AscEmu/issues/1067 and https://github.com/AscEmu/AscEmu/issues/227

Fix NPC equipments in TBC and implement offhand attacks for creatures

---

src/collision/BoundingIntervalHierarchy.h
src/collision/Management/MMapManager.cpp
src/collision/Maps/TileAssembler.cpp
src/collision/Models/GameObjectModel.cpp
src/collision/Models/ModelInstance.cpp
src/collision/Models/WorldModel.cpp
src/logonserver/LogonCommServer/LogonCommServer.cpp
src/logonserver/Server/Master.cpp
src/shared/ByteConverter.h
src/shared/Common.Legacy.h
src/world/Management/Guild/Guild.cpp
src/world/Map/Area/AreaStorage.hpp
src/world/Movement/MovementDefines.cpp
src/world/Movement/MovementGenerators/SplineChainMovementGenerator.cpp
src/world/Movement/Spline/MoveSpline.cpp
src/world/Movement/Spline/Spline.cpp
src/world/Objects/Transporter.cpp
src/world/Server/Master.cpp

Fix non-pch build Classic, TBC, WotLK
Cata+ versions not checked

Fix non-pch build Classic, TBC, WotLK

---

src/scripts/SpellHandlers/LegacyFiles/DeathKnightSpells.cpp
src/world/Chat/Commands/MiscCommands.cpp
src/world/Chat/Commands/NpcCommands.cpp
src/world/Map/Maps/WorldMap.cpp
src/world/Movement/MovementGenerators/IdleMovementGenerator.cpp
src/world/Movement/MovementGenerators/WaypointMovementGenerator.cpp
src/world/Movement/Spline/MoveSplineInit.cpp
src/world/Objects/MovementDefines.hpp
src/world/Objects/Transporter.cpp
src/world/Objects/Units/Creatures/Vehicle.cpp
src/world/Objects/Units/Unit.cpp
src/world/Server/Packets/Handlers/ItemHandler.cpp
src/world/Server/Packets/Handlers/MiscHandler.cpp
src/world/Server/Packets/Handlers/MovementHandler.cpp

In cata and beyond is no Movementflag Transport
Fix: #1100 

Fix Cataclysm Transporters

---

src/world/Spell/SpellProc.cpp
src/world/Spell/SpellProc.hpp

I was not realy sure about the deletion of the pointer sorry i should have testet it more xD
Now the Spell Proc is an shared_ptr and wait until all references are cleared for deletion. I wantet to avoid a situation where the pointer dont gets freed when 2 hold the same reference thats why i used weak_ptr for one....
fix #1146 
- [] Build AE with "TREAT_WARNINGS_AS_ERRORS" flag turned on.
- [] Classic
- [] TBC
- [] Cata

make shared ptr

---

src/world/Storage/MySQLDataStore.cpp

This fixes memory leak in MySQLDataStore::loadCreatureAIScriptsTable().
At base "MySQLStructure::CreatureAIScripts* ai_script = new MySQLStructure::CreatureAIScripts;" is created but function code block has several "continue" operators on invalid data and it never frees memory.
In this PR i added additional "delete" operators to free memory
- None
- [] Build AE with "TREAT_WARNINGS_AS_ERRORS" flag turned on.

Fixed memory leak in MySQLDataStore::loadCreatureAIScriptsTable()

---

src/world/Objects/Units/Creatures/Creature.h

In this PR i'm corrected mistake in SetRespawnTime. I found this error when i was preparing another PR for warning fixes. In general this function result is not set to anything but its purpose is to set respawn time to m_respawnTime variable

Core/Creatures: fixed code mistake in Creature::setRespawnTime

---

src/world/Server/Packets/Handlers/MiscHandler.cpp

Fixed crash in CMSG_WHO. Crash is caused because of incorrect conditional code blocks.
- None

Fixed crash in CMSG_WHO handler

---

src/collision/Models/WorldModel.cpp

array-like pointers needs to be deleted with "delete[]" call
- None

Fixed invalid "delete" operator call in WMOLiquid assign/copy operator

---

src/shared/Database/Field.hpp
src/world/Map/Maps/BaseMap.hpp
src/world/Map/Maps/WorldMap.hpp

fix compilation 
```
[ 57%] Building CXX object src/scripts/Battlegrounds/CMakeFiles/Battlegrounds.dir/cmake_pch.hxx.gch
In file included from /home/ascemu/installer/ascemu_code/src/world/Map/Cells/MapCell.hpp:8,
from /home/ascemu/installer/ascemu_code/src/world/Map/Cells/CellHandler.hpp:9,
from /home/ascemu/installer/ascemu_code/src/world/Map/Maps/WorldMap.hpp:8,
from /home/ascemu/installer/ascemu_code/src/world/Map/Maps/BattleGroundMap.hpp:8,
from /home/ascemu/installer/ascemu_code/src/scripts/Battlegrounds/pchBattleGrounds.hpp:10,
from /home/ascemu/installer/build/src/scripts/Battlegrounds/CMakeFiles/Battlegrounds.dir/cmake_pch.hxx:5,
from <command-line>:
/home/ascemu/installer/ascemu_code/src/world/Map/Maps/BaseMap.hpp:45:10: error: ‘string’ in namespace ‘std’ does not name a type
45 …
```

fix compilation 

---

src/shared/Common.Legacy.h

fix warning C4996: 'strnicmp' The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strnicmp.

fix warning C4996: 'strnicmp'

---

src/scripts/InstanceScripts/Wotlk/IcecrownCitadel/Raid_IceCrownCitadel.cpp
src/scripts/InstanceScripts/Wotlk/VioletHold/Instance_TheVioletHold.cpp
src/world/Server/Script/InstanceScript.hpp
src/world/Server/Script/ScriptMgr.cpp

Fixed Mutex Loop in certain conditions. And fixed scriptEvents being Invalid.
Fixed some minor Mistakes in Instances where a Mutex Loop would crash the server. And scriptEvents not beeing Initialised and being invalid.
- [] Build AE with "TREAT_WARNINGS_AS_ERRORS" flag turned on.

Some Minor Crash Fixes

---

sql/world/updates/20230727-00_trialofcrusader.sql
sql/world/updates/20231123-00_creature_properties.sql
sql/world/updates/20240309-00_spell_ranks.sql
sql/world/updates/20240511-00_creature_properties.sql
sql/world/updates/20240511-01_creature_properties.sql
sql/world/updates/20240904-00_misc.sql
sql/world/updates/20250112-00_world_db_version.sql
src/shared/Database/DatabaseUpdater.cpp
src/world/Server/Master.cpp

- Use regex to ensure unix newlines in database update files.
- Correct world db version ids. Apparently we have skipped id 135.
Closes https://github.com/AscEmu/AscEmu/issues/1214 https://github.com/AscEmu/AscEmu/issues/1209
Tested by having clean new databases and let auto update setup base files and apply all updates.
Tested with Debian and MariaDB, Ubuntu and MySQL, Windows and MySQL.

Fix database updater

---

src/logonserver/LogonCommServer/LogonCommServer.cpp
src/logonserver/LogonCommServer/LogonCommServer.h
src/world/Server/LogonCommClient/LogonCommClient.cpp
src/world/Server/LogonCommClient/LogonCommClient.h

LogonComm: Use additional RC4Engine for packet send
@Zyres I have no idea what I am doing XD but now worldserver instantly registers with logonserver.
I knew that https://github.com/AscEmu/AscEmu/commit/1dcaf276ccf4b2d1b27c0d953198964a9773aaa3 caused the issue so I added sendCrypto back to LogonCommClient/Server.
Tested on Ubuntu and Windows.
Closes https://github.com/AscEmu/AscEmu/issues/1211

Fix worldserver register timeout

---

src/world/Server/Packets/MsgAuctionHello.h
src/world/Server/Packets/MsgChannelStart.h
src/world/Server/Packets/MsgChannelUpdate.h
src/world/Server/Packets/MsgCorpseQuery.h
src/world/Server/Packets/MsgInspectArenaTeams.h
src/world/Server/Packets/MsgInspectHonorStats.h
src/world/Server/Packets/MsgMinimapPing.h
src/world/Server/Packets/MsgMoveTeleportAck.h
src/world/Server/Packets/MsgPetitionDecline.h
src/world/Server/Packets/MsgQuestPushResult.h
src/world/Server/Packets/MsgRaidReadyCheck.h
src/world/Server/Packets/MsgRandomRoll.h
src/world/Server/Packets/MsgSetDungeonDifficulty.h
src/world/Server/Packets/MsgSetRaidDifficulty.h
src/world/Server/Packets/MsgTabardvendorActivate.h
src/world/Server/Packets/MsgTalentWipeConfirm.h
src/world/Spell/Definitions/SpellCastTargetFlags.hpp
src/world/Spell/Spell.cpp
src/world/Spell/SpellCastTargets.cpp
src/world/Spell/SpellInfo.cpp
src/world/Spell/SpellInfo.hpp

Spells: Set implicit target based on effect if it's not existing
Packets: Correct packet sizes in all Msg packets
Closes https://github.com/AscEmu/AscEmu/issues/1210

Spells: Set implicit target based on effect if it's not existing

---

cmake/Compilers/clang.cmake

added support arm
fix build raspberry pi
test pi 5 8gb
Operating System: Debian GNU/Linux 12 (bookworm)  
Kernel: Linux 6.1.0-rpi8-rpi-2712
Architecture: arm64
clang version 14.0.6
gcc    version 12.2.0 (Debian 12.2.0-14) 

fix clang build raspberry pi

---

.github/workflows/clang-linux-test-x64.yml
.github/workflows/gcc-linux-test-x64.yml

Latest version of actions/checkout is 4.2.2. Update our github actions to use it.

Latest version of actions/checkout is 4.2.2. 

---

src/world/Objects/Units/Unit.cpp

test
11:31:50 [ERROR][MAJOR]: Unit::addProcTriggerSpell : Spell id 5301 tried to add a non-existent spell to Unit ****0x7f99b80bdb10**** as SpellProc
You can check the logs, I think you have this error.

fix fmt style
